<?php

namespace Database\Seeders;

use App\Models\Testimonial;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class TestimonialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Deduplicate by reviewer name + description combo
        $seen = [];

        $testimonials = [
            ['Janine S', 'Lake Zurich, IL', 'Fri Nov 13 2020', "GS Construction is a reliable contractor who did top quality work at a reasonable price. We completed a first floor remodel (kitchen renovation with wall removal, half bath remodel, new hardwood floors, updated laundry room) which required carpenters, plumbers, hvac and painters. Their attention to detail is amazing and the work was completed right on schedule. We are beyond thrilled with our updated house! I would recommend GS in a heartbeat and will definitely call on them when it is time to update the rest of the house."],
            ['pawpost', 'Glencoe, IL', 'Mon Apr 27 2015', "We have used GS for two bathroom projects-the first a small update; the second a complete remodel. We were thrilled with both. Everything was as promised; the timeline, price, and what it would look like. We were able to buy our own tile and fixtures and were not tied to any company's showroom. We got what we wanted and likely saved money doing so. GS also installed interior doors. The workmanship was great. The only downside is that now the bathrooms are the two nicest rooms in the house! I would heartily recommend GS construction!"],
            ['Lisa R', 'Vernon Hills, IL', 'Sat May 02 2015', "GS Construction & Remodeling is the best of the best. We've hired them to work on 5 different properties (4 were extensive remodels) and continue to be thrilled with their work and have referred them to friends and family. I constantly bring to them pictures/ideas from Houzz & Pinterest and ask how we can duplicate high end looks on a budget and they pull it off - magnificently - every time. Not only do they know their craft, but they have a great design sense as well and make suggestions that always enhance the project. Their communication (providing estimates for changes as we go along, keeping in touch regarding scheduling, etc.) is excellent. They're nice people and incredibly respectful too - top notch all around."],
            ['Terri F', 'Wheeling, IL', 'Sun May 03 2015', "Greg came highly recommended for my bathroom remodel. From demolition to final product, I was very happy with my choice in contractors! Greg listened to what I wanted done, made some suggestions and even changed tile layout in the tub area after I changed my mind. He wanted me to be completely happy when he was done. He always left the work area clean each day and start each day on time. Because of the workmanship, GS Construction is doing a family member's bathroom remodel. It was an easy choice!"],
            ['Pamela S', 'Rolling Meadows, IL', 'Mon Aug 31 2015', "Using Houzz to find a great contractor who could complete work on 2 small bathrooms, I contacted GS Construction. Greg & Patryk arrived the next early evening to look at my projects. They are courteous and professional. Patryk sent me a detailed estimate by the next evening. After answering all my questions, a date was determined to being construction. Bath #1: Completely gutted and reconstructed. Every thing was taken. The low ceiling in the bathroom was raised by 1 foot, along with installing recessed lighting. The tile work was excellent. LOVE IT. Bath #2: The shower stall had been remodeled the previous year but was constructed wrong, hence water was leaking onto the floor. The walls were taken out and new walls installed, along with new tiled walls and shower floor. All is perfect! I cannot say enough words about the excellent work performed by GS Construction. I highly recommend this company for any project."],
            ['Mark Z', 'Evanston, IL', 'Wed Oct 21 2015', "Greg and Patryk came highly recommended by another client of theirs and I too would highly recommend them. They have done a kitchen renovation for me as well as other carpentry and tiling projects. They are courteous and punctual and respond to all questions in a timely manner. They are a pleasure to deal with."],
            ['J Peterson Design', 'Palatine, IL', 'Wed Oct 28 2015', "Greg and Patryk are the ultimate professionals! I hired them to do a detailed kitchen project for my client. First, they were very friendly and approachable with me and the client, which is not often the case with contractors. It was obvious after interviewing them that they were experienced and skilled at what they do. They asked questions every step of the way to make sure the job was perfect, from how I needed the moulding done to the exact location of the island lights. There was no delay in the project, they were there when they said they would be there. There was not one little thing left undone. When the client asked for some items to be added to the contract they were happy to do it. I am looking forward to working with GS construction for my next projects. Highly recommend!"],
            ['Drew S', 'Mount Prospect, IL', 'Mon Nov 02 2015', "We found G&S on Houzz.com and couldn't be happier. They created a full basement bathroom and did drywall work to enclose a section of the basement to create a small 4th bedroom. Not only was the price reasonable but their communication and quality of work were outstanding. They did a weekly walk through during the project which was helpful to gage the progress of the project and to make any change requests. This was our first large house project and they guided us through the entire process. I would definitely recommend them and we plan to use them in the future."],
            ['Donna M', 'Evanston, IL', 'Sat Nov 07 2015', "My designer and I chose GS Construction for the rehab of my kitchen and other small projects in my newly purchased condo. They were recomended by a client of the designer, Mark Zancanaro Design, who raved about their professionalism and communication, as well as their skill. It was the best decision I made. Greg and Patryk were prompt, courteous and extremely knowledgeable. They listened to what I wanted and their attention to detail was greatly appreciated. They were not satisfied until everything was absoutley perfect. I would highly recommend them to anyone looking for a reliable and skilled construction company to complete any size project in their home or office. They will definitley be called for any future projects in my new home."],
            ['Tracey B', 'Hoffman Estates, IL', 'Thu Dec 10 2015', "My designer, Jennifer Peterson, discovered GS Construction for us and we hired them for our kitchen renovation. Greg & Patryk are consummate professionals and I would recommend them to my friends and family, as well as hire them again for my next remodeling project. They stayed on schedule and on budget, and their attention to detail and craftsmanship was outstanding. There are not enough words to cover how thrilled my husband and I are with their work."],
            ['Scott N', 'Chicago, IL', 'Mon Dec 14 2015', "Patryk and Greg did the work on a custom kitchen refresh and complete lighting overhaul in our 2 bedroom condo in Bucktown, Chicago. My wife and I couldn't be more pleased with the results but also the entire process. Patryk was incredibly accessible and helpful along the way. The work screams quality. When we move to our next home, already looking forward to working with these guys again. Highly recommend."],
            ['Erin A', 'Palatine, IL', 'Thu Sep 15 2022', "Patryk (and team) were the best to work with. They helped us with a remodel on our basement (including the addition of a dry bar about 4 months later) and we couldn't be happier with the finished product. They were transparent with us through the entire project (through crazy supply chain issues). When they couldn't get something they were up front with us providing options that might be easier to secure to finish the project in a more timely manner. His entire team is honesty so delightful to work with and have in my home. I've had contractors in my house where it's somewhat uncomfortable and Patryk's team is all amazing. The communication about when they would be coming by was seamless. And as a woman (who was basically running this project) they weren't condescending or rude to me either. I cannot wait to work with them again and would hire them in a heartbeat."],
            ['Bruce L', 'Buffalo Grove, IL', 'Mon Feb 01 2016', "In a word, superb. This is the first time I've taken the trouble to review a contractor. We hired GS Construction to remodel a bathroom. The job took about 3 weeks; during that time, they were always on time and didn't miss a single day. They were exceptionally easy to work with and extremely pleasant. They had good ideas, and the bathroom turned out better than we expected. Even when they were not at our home doing the work, they were easy to contact and always responsive regardless of whether we called in the evening or on a weekend. I recommend them highly and plan to use them again."],
            ['Kristen C', 'Chicago, IL', 'Tue May 17 2016', "Greg & Patryk are a dream team. My husband and I have hired them for numerous projects on our home in Lincoln Park and we could not be happier with the results. Every day they showed up on time and left our home spotless each night. They are reliable, responsible and completely professional. Each project was completed on time and within budget. They are also great problem solvers. We have recommended GS Construction to our neighbors who have also been completely happy with their work as well. We are thrilled we have built this relationship and look forward to working with them in the future."],
            ['Lu H', 'Chicago, IL', 'Fri May 20 2016', "You will not regret choosing GS Construction & Remodeling. We are beyond happy with our condo remodel, and it is all thanks to Greg, Patryk, and their team of hardworking and meticulous professionals. We completely remodeled our two bedroom, two bathroom Bucktown condo. Greg and Patryk listened to all of our ideas, and they suggested many of their own ideas that improved the project. They worked well with our designer. Greg and Patryk worked diligently to stage the construction to intrude into our life as minimally as possible. They took such care of our belongings, and were careful and organized with the numerous materials and supplies. We could not believe that it only took about 5 weeks to gut and replace our kitchen, bathrooms, bedrooms, closets – not to mention brand new hardwood floors throughout. Greg and Patryk even worked with us to create an office nook at the end of a hall way that created a new \"room\" in our home. Greg, Patryk, and the professionals they subcontracted could not have been nicer. The quality of the work is impeccable, and if there was anything we wanted changed, Greg and Patryk came back to make adjustments. It was so easy to communicate with them, and we always felt that they had our best interest, style, and budget in mind. The results of our large-scale project speak for themselves. We highly recommend GS Construction & Remodeling to anyone who is interested in redoing any part of their home."],
            ['Tara B', 'Lake Zurich, IL', 'Mon Jun 06 2016', "GS Construction did a fabulous job remodeling my kitchen/dining room! They finished the job on time, listened to our concerns, answered our questions, and stayed within our budget! Very professional, I would definitely recommend them!"],
            ['kalorama', 'Buffalo Grove, IL', 'Sun Jun 12 2016', "They did an outstanding job on our complete bathroom renovation! Our bathroom was an icebox due to poor insulation from the original build. They made excellent design recommendations to resolve the poor insulation and also installed heated floors. They converted an outdated tub/ shower combo into a beautiful walk-in shower and we are thrilled with the results. Their team was prompt, courteous and clean, taking off shoes and wiping down the area which with a toddler in the home was extra appreciated. They even helped us install a shower rod in another bathroom that was not part of the project. We are so happy they were recommended to us and we would definitely recommend them for your project."],
            ['Karen B', 'Chicago, IL', 'Fri Jul 01 2016', "GS Construction worked on my condo renovation. Patryk had wonderful insight on details that that other potential contractors didn't even think of. They took all surprise issues in stride, and solved them before I even knew about the issues! I work full-time and could not be present during work hours, but Patryk communicated well and worked around my schedule. They understood my personal style and added small finishing touches that align perfectly with the design."],
            ['Carole U', 'Lake Zurich, IL', 'Sun Oct 09 2016', "Hire this company! GS Construction was hired to gut and remodel my kitchen/dining area and master bathroom. I elected to hire them over other contractors in large part due to Patryk's vision and their detailed bid on the project. When looking at the master bath, Patryk asked, \"Would you like a larger shower?\" and detailed how the shower could be expanded in my tiny bathroom with a minimum of extra work. The other contractors didn't make this suggestion and since I am not a contractor, I didn't know that it was even an option. Mid way through the project, I decided to remodel my second bathroom as well. Greg and Patryk were able to accommodate my request, which I'm sure threw their schedule out of whack. I had to live in my small house (along with my three dogs) during the remodel. I wouldn't recommend it if you have other options, but GS worked around me without a problem - always keeping a bathroom in working order! Patryk is great at keeping you up-to-date regarding what happened on a daily basis and what is going to happen the following day. They worked every day unless waiting for inspections to take place. The workers arrived at the scheduled time and cleaned up (as much as possible) at the end of the day. They stayed very close to the schedule in spite of some unexpected things that came up and stayed on budget. I often hear nightmare stories of remodel projects gone bad, working with GS construction was a dream. This was my first major remodel and if I ever need work in the future, I will call GS Construction."],
            ['Jill M', 'Arlington Heights, IL', 'Sat Oct 15 2016', "I have never enjoyed working on a project as much as I did with our recent kitchen remodel. Patryk & Greg make an incomparable team -- organized, detail-oriented and right on schedule! They answered any questions I had and exceeded my expectations on work quality, cleanliness of the work space and ease of collaboration. When there was a tile delay when we slightly modified the design, they simply worked around it and were still able to complete the job within the original timeline. They partnered seamlessly with our designer, Jennifer Peterson and I trusted them to be in my home while I was at work due to their professionalism. They are creative, consummate craftsmen whom I would hire again in a heartbeat!"],
            ['Melanie H', 'Palatine, IL', 'Sat Dec 17 2016', "GS construction just remodeled my kitchen and I could have not been more pleased with the work they have done. Greg and Patryk were reliable, always on time and very responsive. They were always willing to work with any changes that were made during the construction their work was top notch. They made sure that all the work that was done was perfect and top quality. They made sure the house was always put back together and cleaned up before they left would recommend them to all my friends and family."],
            ['Lori O', 'Arlington Heights, IL', 'Wed Jan 11 2017', "GS Construction did a great job with construction of our kitchen remodel. Very knowledgeable, trustworthy, detail oriented and easy to work with. They are a full service operation so we didn't have to worry about hiring outside contractors for electrical, plumbing, painting, etc... We are more than pleased with the end result and plan on using them again in the future for other projects."],
            ['Doug K', 'Palatine, IL', 'Thu Sep 15 2022', "GS Construction is our #1 Home Remodeling team! Patryk, Greg and his entire remodeling team are friendly, professional and always do an amazing job working with us to configure/tailor the project to fit our needs. We have used GS Construction for a full basement remodel, kitchen remodels and an upstairs bath remodel. I can't say enough good things about Patryk and GS Construction, they deliver on the entire job from start to finish & always keep me informed throughout."],
            ['Peter V', 'Palatine, IL', 'Mon Feb 13 2017', "Patryk and Greg are a great team. It was a real pleasure working with GS construction. There were a few things that my wife and I were looking for in a contractor before we started our Master bedroom/bathroom remodel and hall bathroom remodel. Quality workmanship, timely job completion, and respect of our budget. We got all three with GS construction. Every member of their crew was a pleasure to work with and they did a great job. One thing we wanted to make sure was that we didn't compromise any design concepts or materials because of budget issues. Patryk and Greg worked with us to reduce costs on certain aspects of the project so we didn't lose anything we were really excited about including in the project. We would definitely use them again for any home remodeling or special projects around the house. Thanks again."],
            ['Barbara M', 'Arlington Heights, IL', 'Thu Jun 01 2017', "GS Construction did a complete home renovation for me - taking about 6 months to complete. They were great to work with, offered suggestions, very responsive, patient and above all quality workmanship. I cannot say enough positive things about them."],
            ['Neal & Ivana S', 'Palatine, IL', 'Sun Jul 23 2017', "Absolutely incredible. Words cannot fully express how great these guys are, but we'll try. Greg and Patryk, from the moment we met, were honest, dependable, hard working, and just genuinely nice guys. During the first meeting, they toured the house, laughed at its quirks (in a nice way) and told us how they'd help us make it perfect. We instantly knew they were the right team. Greg and Patryk work closely with our talented designer J.Peterson Design, so they maintained almost daily contact to ensure our vision became reality. After hearing countless stories of contractor nightmares, we can honestly say that there was nothing negative to say. Their quote was extremely detailed and was right in line at the end. We did make some mid-project revisions, but they were completely transparent about what the cost and time impacts would be. Their entire team was extremely skilled and their attention to detail was extraordinary. We are beyond happy with the project and were truly a bit sad to see them go. We talk regularly about when we can start our next project with Greg and Patryk."],
            ['Liz H', 'Kildeer, IL', 'Thu Aug 24 2017', "Patryk and Greg were a pleasure to work with. Not only did they have wonderful communication, keeping us updated on daily progress, they were fast and reliable as well. When a problem arose with our tub, Patryk took the lead and dealt with the retailer and manufacturer so we didn't have to worry. They did amazing work and we are so pleased with our final bathroom! We will definitely use them again!"],
            ['Adam S', 'Chicago, IL', 'Wed Aug 30 2017', "I cannot say enough good things about GS Constructions / Greg and Patryk Szady. From the start, their proposal and cost estimate was broken down, item by item, which most contractors don't do. It allowed us to alter our project to fit our budget. Patryk also took the time to explain costs to us and help us get what we wanted for the price we could afford. Once we hired GS, they kept to their timeline, and they focused on our project. Each day we knew when to expect workers (who came on time!) and at the end of each day, we could see real progress. The crews that came to do the work were courteous, respectful of our space, and they cleaned up after themselves. Patryk and Greg didn't just show up once or twice; they were there throughout the project, and were alway helpful in answering questions, addressing concerns, and making it feel like my project was their main focus. Most importantly, the finished product was beyond our expectations. Patryk and Greg really pay attention to detail and are willing to go the extra mile to make things perfect. From exact tile or light placement, to thinking about how cabinets will sit near a doorway, to vent color, they thought of and addressed issues I hadn't even considered, and they made it look perfect, even when that meant more work for them. When I picked a paint color I ended up not loving, they offered to repaint even though it was my mistake. When I picked a wall mounted faucet known for being difficult, they spent hours trouble shooting water pressure and placement in order to get it just right. When the project was all done, Patryk and Greg followed up a few weeks later to make sure we were happy, and come back and address small punch list items that we realized only after living in the space again. It is this kind of attention to satisfaction and attention to detail that is rare to find in this industry, and it makes Patryk and Greg an absolute pleasure to work with. I have recommended them to others we have been equally happy. TL;DR: GS Construction was on time and on budget, and their prices are competitive and fair. Their work was absolutely beautiful, and we couldn't be more pleased. After this experience, I honestly would not use anyone else. I will be a returning customer for life."],
            ['Madelyn & John K', 'Wilmette, IL', 'Sat Sep 02 2017', "We cannot say enough good things about GS Construction and about Greg and Patryk. We hired them on a strong recommendation from a friend and are very pleased with the results. Our project included remodeling a kitchen and master bathroom and adding wood floors to several rooms in our condo. We had definite ideas of what we wanted since we have done many remodeling projects in several previous homes, but both Patryk and Greg added great value with suggestions and ideas of their own based on their experience and talent. Their follow through was excellent and we feel confident that if anything needs attention, they will be there to make it right. P.S. They did a great clean up at the end of the project......"],
            ['Susana D', 'Arlington Heights, IL', 'Tue Sep 19 2017', "Gregory, Patryk and the whole team were a pleasure to have in my home while they worked on our bathroom remodel. They did a great job on the bathroom..we love it. And we plan to hire them again for our other future home projects. And the best part is that they finished on time...quick and painless."],
            ['Mark B', 'Lake Zurich, IL', 'Wed Jan 10 2018', "We hired Greg & Patryk's GS Construction in August 2017 (recommended by our designer) to remodel our kitchen from the ground up, and have never had as positive an experience with any contractor, ever. We knew we felt comfortable with them from the moment that they came in to do the estimate (super nice guys; always pleasant to deal with), and their work was uniformly excellent, professional, on-time and without any nasty cost surprises. Greg and Patryk are truly client-oriented, and made sure at every decision point that things would be done in a way that would make us happy. They flexibly incorporated change orders that we invented during the middle of the project (like wallpaper instead of just painting) and still managed to finish everything prior to the agreed deadline. The excellence of their work extended from them to every other professional they brought onto the job -- from exquisitely skilled carpenters doing finely detailed work in odd spaces to heating pros to electricians to a fantastic team of paper hangers. Greg/Patryk also went above and beyond in several respects, for example working (no extra charge) on a plumbing issue in the ceiling over the kitchen even though the leak they discovered had nothing to do with their work. Going forward, we would only consider additional projects in our home when GS Construction is available to work on them!"],
            ['Pauline & Scott Z', 'Long Grove, IL', 'Thu May 03 2018', "I don't even know where to begin, Patryk & Greg are just amazing! We hired them to remodel approximately 4000 sqft of a 1985 house which included an unfinished basement. The whole experience could not have been better. It took about 7 months and for most of it, we lived in the house with two children. They are incredibly professional, can troubleshoot any issue and are 100% dependable. Patryk led the project and he was very detail-oriented. Everything had a purpose and was finished with beautiful extra touches. I changed my mind frequently and they didn't miss a beat. They worked around the changes and kept moving. The materials they used and the teams they brought in were all top notch. They didn't spend money where it wasn't necessary and in fact, they were always trying to find ways to save money. Finally, they are really nice guys. Polite, respectful and very accomodating. After spending so long in my house, we (almost) miss having the around."],
            ['Erika E', 'Arlington Heights, IL', 'Fri Sep 14 2018', "GS Construction remodeled our kitchen and family room. They did an amazing job and we enjoyed working with them. We would not hesitate to hire them again."],
            ['Teresa M', 'Inverness, IL', 'Wed Dec 21 2022', "We worked with Patryk and Greg on a first floor remodel, including our kitchen. We couldn't be happier with the results. They kept the project moving along at all times and their workmanship was high quality. Highly recommend GS Construction."],
            ['Mary G', 'Palatine, IL', 'Sat Dec 08 2018', "We had excellent results with GS Construction and would highly recommend them for your project needs. Patryk and Greg walked us through the entire project and offered advice on our many design options. We found a contractor we could trust and enjoy working with. They gave us realistic cost expectations and a payment schedule and always backed up their work. LOVE,LOVE,LOVE the complete update of two bathrooms in our home."],
            ['Teresa S', 'Palatine, IL', 'Sat Feb 23 2019', "G&S is an amazing group of people who can manage a project and come up with \"out of the box\" solutions to satisfy every client. While working on our second bath and our master kitchen, Greg came up with an idea on how to blend two different moldings to look the same in a completely different room (just because I asked). Sounds simple enough, but it posed some challenges to this DIYer. Also, their work is done with precision and expertise. Our second bath still looks like it did two years ago, and our teenagers love it!"],
            ['John B', 'Deer Park, IL', 'Wed Mar 13 2019', "We learned of GS Construction through acquaintances who had hired them for two kitchen remodels, and subsequently hired them for our new hardwood oak floors, kitchen remodel, and conversion of a half bath to a full bath. Greg and Patryk were fantastic and so was everyone on their team. Incredible workmanship, respect, and attention to detail. Every project will have a few unexpected curveballs, but not every project will have a contractor who deals with them so seamlessly. We were proactively told of any timeline adjustments or accelerations and always kept in the loop. The level of communication was fantastic. We are extremely happy with our remodeled home and would definitely hire GS Construction again!"],
            ['Alan H', 'Lake Zurich, IL', 'Thu Dec 12 2019', "I have to admit I was very impressed with their work. The remodeling took approximately three months and the results are beautiful! Greg, Patryk and the entire crew from the demolition team, carpenters, electricians and plumbers did an over the top remodeling of our kitchen and several other rooms. They kept a good timeline to completion and always resolved any questions we had. Very friendly and dedicated people which is so important to find these days. We would gladly hire them again for future projects around our home."],
            ['Kathy W', 'Palatine, IL', 'Mon Dec 16 2019', "Patryk and Greg were recommended to us by our Kitchen Designer. They exceeded our expectations in every way. They were priced very reasonably, the project timeline was right on track and their follow through with any issues went above and beyond expectations. They created the most interesting wine cellar in our kitchen, we get countless compliments on it. We would highly recommend them to anyone doing any type of remodeling or building project."],
            ['Carol T', 'Hoffman Estates, IL', 'Thu Jun 30 2022', "We had a truly amazing experience with GS Construction remodeling our kitchen and first floor. As remodeling novices, we connected with GS Construction through our designer and were so happy with this match made in heaven. Having heard horror stories from friends about remodels that went on forever and tales of unreliable contractors who don't communicate, we were nervous when we started and expected the process to be long and painful. Our experience could not have been more different. Greg and Patryk were great at keeping us informed and the total amount of time from demo to the unveiling to friends and family was really reasonable at a little over 2 months. We received great personalized attention and they were great at offering ideas and trouble shooting various things that came up. But the real highlight is the quality of the work. They were so attentive and made sure that we loved every inch of our new space. We have never loved our house more!"],
            ['Archadeck of Chicagoland', 'Palatine, IL', 'Fri Aug 26 2022', "Great company to work with and did great work on our kitchen / first floor remodel. From restructuring walls to making sure the detail came together they were professional and provided great results. Highly recommend Patryk and his team for anyone's kitchen remodel."],
            ['Trip F', 'Arlington Heights, IL', 'Wed Jan 18 2023', "I did not realize I haven't written a review of GS yet. We remodeled our kitchen during the summer of 2020. Patryk was outstanding. He was even ahead of our estimated timeline by the end of the project (we were held up a little because of our cabinets - Patryk obviously couldn't control that, but he did make sure that other tasks were completed so that when the cabinets did come in, we still basically finished on time). The professionalism was top notch, and the quality was outstanding. I would recommend GS for any project."],
            ['Jason & Becky H', 'Arlington Heights, IL', 'Wed Dec 21 2022', "We worked with Patryk and Greg on a first floor remodel, including our kitchen. We couldn't be happier with the results. I highly recommend working with them. They are very professional and they keep the project moving along. Their workmanship is high quality, too!"],
            ['Carrie & John K', 'Mount Prospect, IL', 'Wed Feb 01 2023', "Greg and Patryk do amazing work and are incredible to work with! GS Construction completed two extensive bathroom renovations for us, including completely reconfiguring layouts and expanding one. Both bathrooms are absolutely beautiful, and they have significantly improved our family's quality of life in our home. Patryk and Greg are great communicators, take pride in their work, and have good attention to detail. Throughout the project, they really listened to us, took the time to understand what we wanted, kept progress going in a timely manner, and provided expert advice/suggestions and help on specific questions along the way. Every one of their team members did high-quality work. We couldn't be happier with the end result, and definitely will hire them for future renovations!"],
            ['Philip E', 'Palatine, IL', 'Mon Apr 10 2023', "Greg and Patryk installed the original Fireplace Mantle (and gas log insert) back into our 1885 Victorian! they did an outstanding job and all of their workers were kind, respectful and trustworthy! We highly recommend GS for any of your home project needs!"],
            ['Kathy & Mike M', 'Arlington Heights, IL', 'Fri Nov 24 2023', "We recently completed a near-total first floor renovation in which we re-drew the original (1963) floorplan. When we selected GS Construction, we had faith that our project would be completed to our specifications but, admittedly, we would not really know for sure until we were finished. Five months later, we can say we were extremely pleased with GS Construction – with the final result and the process itself. From the very beginning, it was clear that Greg and Patryk were \"on top\" of our project. Before demolition, they offered a clear plan and timeline about what we could expect. When demolition began, they communicated almost daily to tell us what was next, what decisions we needed to make and when workers would be on site. From demolition to final inspection, there were fewer than five days when workers were not actively working on site. Greg and Patryk were also terrific partners in helping us make the best decisions for our home. They considered what we were trying to accomplish and how to best achieve it – for function and for cost savings. They handled our changes easily, always working to minimize costs. One of the other things that we came to appreciate from Greg and Patryk was the quality of the work supplied by their sub-contractors. They were top notch and so respectful to us in our home. That, we believe, is a reflection on Greg and Patryk as well. All the tradespeople had very high standards. It's clear that Greg and Patryk set an expectation for the highest quality work and their teams delivered. We wholeheartedly would recommend GS Construction for any home renovation project. High quality work – on time – on budget with a fully engaged and contributing father and son team that was a pleasure to work with."],
            ['James P', 'Inverness, IL', 'Mon Dec 18 2023', "GS Construction was the contractor recommended to us for our remodeling project by our designer, Jenn Peterson of J. Peterson Design. The project involved gutting most of the first floor and doing a complete remodel of the kitchen and family room on a 53 year-old home. We could not be more pleased with the work, responsiveness, timeliness and the outcome. Greg and Patryk (Greg's son) are great people. They worked seamlessly with Jenn and had no issue with working to change some of the plans on the fly. They identified some structural issues natural to an older home and resolved them quickly and in very cost-effective ways. We had more contact with Patryk, who walked us through the project step by step from beginning to end. He was always available to talk to us and kept the project on schedule. Any change orders or other modifications were handled quickly and professionally. We recommend GC Construction without any reservations. They do great work and were fun to work with as well."],
            ['Taylor D', 'Palatine, IL', 'Tue Jun 11 2024', "Patryk and his team did an incredible job on our home. We gutted nearly every room and they executed our vision perfectly. Patryk is a great communicator, has fair pricing, and does quality work that holds up. Everyone that comes to our home remarks on what an incredible transformation they accomplished."],
            ['Ron & Denise M', 'Lake Zurich, IL', 'Sat Sep 07 2024', "Our project turned out better than we expected and as things were going along, we added more projects. Patryk, Greg and their team did a fantastic job. They were always so nice to work with, even suggesting things which was helpful. They never left a project until they thought it was perfect. We did a full kitchen remodel, even closing off a window to move a fridge and pantry to the other side to allow more cabinets and much needed counter space. They widen the entrance and the kitchen seems so much bigger. We think it's Beautiful! They did laminated floors throughout the first floor, painted all walls and new baseboards. They created a wine bar which was just a cubby hole. They put in a pantry like cubby hole in our laundry room and added cabinets and above wall unit. One of the projects we had them add is new wooden stairs to the 2nd floor, white spindles and railing that curves instead of a wall and laminate floors on the 2nd floor. Other odd and ends that they never hesitated to do. We appreciate all they have done in our home, To us, it's amazing how nice it is and how it should have been all the years we have lived here. Its exciting to show it off, it feels like a new house. These guys are amazing and would definately recommend them to anyone. Very reliable and easy to get in contact with when needed."],
            ['Barb D', 'Arlington Heights, IL', 'Fri Mar 24 2023', "G&S construction did a complete renovation of my bathroom. They came highly recommended and they did a wonderful job. I felt very comfortable giving them my house key so that they could come and go while I was at work. I love my new bathroom!"],
            ['Alex K', 'Chicago, IL', 'Mon Apr 27 2015', "I am a designer in Chicago and worked with Greg and his team on two bathroom renovations. They were exceptional. Their communication was really impressive, they were on time, on budget and fantastic to work with. I really have nothing but good things to say. I really look forward to working with them again in the near future. A great contractor is hard to come by, but I would recommend GS to anyone!"],
        ];

        foreach ($testimonials as $t) {
            $key = $t[0] . '|' . substr($t[3], 0, 100);
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;

            Testimonial::create([
                'reviewer_name' => $t[0],
                'project_location' => $t[1],
                'review_date' => Carbon::parse($t[2]),
                'review_description' => $t[3],
            ]);
        }
    }
}
