<?php

namespace App\Services;

use App\Models\AreaServed;
use App\Models\Project;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;

/**
 * Builds the ZIP -> {city, area, projects} map used for /service-area/{zip}
 * landing pages and sitemap generation.
 *
 * Source of truth for ZIP coverage: hive_project_zip_counts table
 * (populated by `php artisan hive:sync` from hive.contractors).
 *
 * City attribution comes from storage/app/seo/zip-city-map.json
 * (generated by seo:sync-zip-cities), with a safe fallback label.
 */
class ZipCodeService
{
    /**
     * Get area slugs within a given radius (miles) of a ZIP code.
     * Returns array of area slugs (including the center area if found).
     */
    public function getNearbyAreaSlugs(string $zip, float $radiusMiles = 10.0): array
    {
        $zip = preg_replace('/\D/', '', $zip);
        $map = $this->getZipMap();
        $info = $map[$zip] ?? null;
        if (! $info || ! $info['area_slug']) {
            return [];
        }
        $area = AreaServed::where('slug', $info['area_slug'])->first();
        if (! $area || $area->latitude === null || $area->longitude === null) {
            return [$info['area_slug']];
        }
        // Find all areas within radius using Haversine.
        $haversine = '(3959 * acos(cos(radians(?)) * cos(radians(latitude)) '
            . '* cos(radians(longitude) - radians(?)) '
            . '+ sin(radians(?)) * sin(radians(latitude))))';
        $areas = AreaServed::query()
            ->select('slug')
            ->selectRaw("{$haversine} AS distance_miles", [$area->latitude, $area->longitude, $area->latitude])
            ->whereNotNull('latitude')
            ->whereNotNull('longitude')
            ->having('distance_miles', '<=', $radiusMiles)
            ->get();
        return $areas->pluck('slug')->unique()->values()->all();
    }
     private const CACHE_KEY = 'service_area:zip_map:v4';
    private const CACHE_TTL = 86400; // 24h

    /**
     * @return array<string, array{city: string, area_slug: ?string, project_ids: array<int,int>, count: int}>
     */
    public function getZipMap(): array
    {
        return Cache::remember(self::CACHE_KEY, self::CACHE_TTL, function (): array {
            $allZips = app(\App\Services\HiveProjectsClient::class)->storedZips();
            if (empty($allZips)) {
                return [];
            }
            $allZips = array_flip($allZips);

            $zipCityMap = $this->loadZipCityMap();

            // city (lowercased) => area slug
            $areaBySlug = AreaServed::all(['city', 'slug'])
                ->mapWithKeys(fn ($a) => [mb_strtolower(trim($a->city)) => $a->slug])
                ->all();

            // Group published projects by normalized city name.
            $projectsByCity = [];
            $projects = Project::query()
                ->where('is_published', true)
                ->get(['id', 'location']);
            foreach ($projects as $p) {
                $city = trim(explode(',', (string) $p->location)[0] ?? '');
                if ($city === '') {
                    continue;
                }
                $cityKey = mb_strtolower($city);
                $projectsByCity[$cityKey][] = (int) $p->id;
            }

            // zip => [city, area_slug, project_ids[]]
            $zipMap = [];

            foreach (array_keys($allZips) as $zip) {
                $city = $zipCityMap[$zip] ?? 'Chicagoland';
                $cityKey = mb_strtolower($city);
                $projectIds = $projectsByCity[$cityKey] ?? [];

                $zipMap[$zip] = [
                    'city' => $city,
                    'area_slug' => $areaBySlug[$cityKey] ?? null,
                    'project_ids' => $projectIds,
                    'count' => count($projectIds),
                ];
            }

            ksort($zipMap);
            return $zipMap;
        });
    }

    /**
     * @return array<string, string>
     */
    protected function loadZipCityMap(): array
    {
        // Source of truth #1: hive_project_zip_counts table. The Hive sync
        // populates `city` per zip from the contractors source, so this is
        // available on every environment that has run `php artisan hive:sync`
        // (no separate seo:sync-zip-cities step required).
        $out = [];
        try {
            $rows = \App\Models\HiveProjectZipCount::query()
                ->whereNotNull('city')
                ->where('city', '!=', '')
                ->select('zip', 'city')
                ->distinct()
                ->get();
            foreach ($rows as $row) {
                $zip = preg_replace('/\D/', '', (string) $row->zip);
                $city = trim((string) $row->city);
                if (strlen((string) $zip) === 5 && $city !== '') {
                    $out[$zip] = $city;
                }
            }
        } catch (\Throwable) {
            // Table missing (fresh install) — fall through to JSON only.
        }

        // Source of truth #2 (override): storage/app/private/seo/zip-city-map.json.
        // Wins over the Hive value when both are present, so manual curation
        // via seo:sync-zip-cities can correct any odd city labels from Hive
        // (e.g. "Glenview Nas" -> "Glenview").
        $path = 'seo/zip-city-map.json';
        if (Storage::disk('local')->exists($path)) {
            $decoded = json_decode((string) Storage::disk('local')->get($path), true);
            if (is_array($decoded)) {
                foreach ($decoded as $zip => $city) {
                    $zip = preg_replace('/\D/', '', (string) $zip);
                    $city = trim((string) $city);
                    if (strlen((string) $zip) === 5 && $city !== '') {
                        $out[$zip] = $city;
                    }
                }
            }
        }

        return $out;
    }

    /**
     * @return array{city: string, area_slug: ?string, project_ids: array<int,int>, count: int}|null
     */
    public function find(string $zip): ?array
    {
        $zip = preg_replace('/\D/', '', $zip);
        $map = $this->getZipMap();
        return $map[$zip] ?? null;
    }

    /**
     * Convenience: list of ZIPs grouped by city.
     *
     * @return array<string, array<int, string>>
     */
    /**
     * ZIPs grouped by city, for the /service-area index.
     *
     * Restricted to ZIPs that belong to a town in the admin area list. The map
     * itself is built from hive_project_zip_counts — everywhere we have ever
     * completed a job — which is a wider net than the service area we publish:
     * it was listing Naperville, Wheaton, Hinsdale, Oak Lawn and 7 others that
     * were deliberately not in the curated area list.
     *
     * Only the LISTING is filtered. getZipMap()/find() stay unfiltered on
     * purpose, so /service-area/{zip} pages that are already indexed keep
     * returning 200 instead of turning into 404s.
     */
    public function groupedByCity(): array
    {
        $grouped = [];
        foreach ($this->servedZipMap() as $zip => $info) {
            $grouped[$info['city']][] = (string) $zip;
        }
        ksort($grouped);
        return $grouped;
    }

    /**
     * The ZIP map restricted to towns in the admin area list.
     *
     * getZipMap() is built from hive_project_zip_counts — everywhere we have
     * ever completed a job — which is a wider net than the service area we
     * publish. It was surfacing Naperville, Wheaton, Hinsdale, Oak Lawn and 7
     * others that were deliberately not in the curated list.
     *
     * This is the one definition of "served", shared by the /service-area
     * index, the sitemap and the generated ZIP content, so the three cannot
     * drift. getZipMap() stays unfiltered because ZipCodePage still needs to
     * RECOGNISE an unserved ZIP in order to redirect it rather than 404.
     *
     * @return array<string, array{city: string, area_slug: ?string, project_ids: array<int,int>, count: int}>
     */
    public function servedZipMap(): array
    {
        $servedSlugs = AreaServed::query()->pluck('slug')->flip();

        return array_filter(
            $this->getZipMap(),
            fn (array $info): bool => $info['area_slug'] && $servedSlugs->has($info['area_slug'])
        );
    }

    /** True when the ZIP resolves to a town we actually publish. */
    public function isServed(string $zip): bool
    {
        return isset($this->servedZipMap()[preg_replace('/\D/', '', $zip)]);
    }

    /**
     * The published projects a ZIP service-area page renders, newest first.
     *
     * Extracted from ZipCodePage so the sitemap can declare the photos the page
     * actually shows. These pages pick projects from every area within 10 miles
     * of the ZIP, which is a different set from an area page's localProjects()
     * — declaring the area's set here would advertise images that aren't on the
     * page, so the two must come from one place or they drift.
     *
     * @return \Illuminate\Database\Eloquent\Collection<int, Project>
     */
    public function projectsNear(string $zip, int $limit = 12): \Illuminate\Database\Eloquent\Collection
    {
        $nearbyAreaSlugs = $this->getNearbyAreaSlugs($zip, 10.0);

        $cityKeys = AreaServed::whereIn('slug', $nearbyAreaSlugs)
            ->get()
            ->map(fn ($a) => mb_strtolower(trim((string) $a->city)))
            ->unique()
            ->values()
            ->all();

        $ids = collect();
        foreach ($cityKeys as $cityKey) {
            $ids = $ids->merge(
                Project::query()
                    ->where('is_published', true)
                    ->whereRaw('LOWER(TRIM(SUBSTRING_INDEX(location, ",", 1))) = ?', [$cityKey])
                    ->pluck('id')
            );
        }

        return Project::query()
            ->whereIn('id', $ids->unique()->values())
            ->where('is_published', true)
            ->with('images')
            ->orderByDesc('updated_at')
            ->limit($limit)
            ->get();
    }

    public function flush(): void
    {
        Cache::forget(self::CACHE_KEY);
    }
}
