<?php

namespace App\Services;

use App\Models\AreaServed;
use App\Models\Project;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;

/**
 * Builds the ZIP -> {city, area, projects} map used for /service-area/{zip}
 * landing pages and sitemap generation.
 *
 * Source of truth for ZIP coverage: hive_project_zip_counts table
 * (populated by `php artisan hive:sync` from hive.contractors).
 *
 * City attribution comes from storage/app/seo/zip-city-map.json
 * (generated by seo:sync-zip-cities), with a safe fallback label.
 */
class ZipCodeService
{
    /**
     * Get area slugs within a given radius (miles) of a ZIP code.
     * Returns array of area slugs (including the center area if found).
     */
    public function getNearbyAreaSlugs(string $zip, float $radiusMiles = 10.0): array
    {
        $zip = preg_replace('/\D/', '', $zip);
        $map = $this->getZipMap();
        $info = $map[$zip] ?? null;
        if (! $info || ! $info['area_slug']) {
            return [];
        }
        $area = AreaServed::where('slug', $info['area_slug'])->first();
        if (! $area || $area->latitude === null || $area->longitude === null) {
            return [$info['area_slug']];
        }
        // Find all areas within radius using Haversine.
        $haversine = '(3959 * acos(cos(radians(?)) * cos(radians(latitude)) '
            . '* cos(radians(longitude) - radians(?)) '
            . '+ sin(radians(?)) * sin(radians(latitude))))';
        $areas = AreaServed::query()
            ->select('slug')
            ->selectRaw("{$haversine} AS distance_miles", [$area->latitude, $area->longitude, $area->latitude])
            ->whereNotNull('latitude')
            ->whereNotNull('longitude')
            ->having('distance_miles', '<=', $radiusMiles)
            ->get();
        return $areas->pluck('slug')->unique()->values()->all();
    }
     private const CACHE_KEY = 'service_area:zip_map:v4';
    private const CACHE_TTL = 86400; // 24h

    /**
     * @return array<string, array{city: string, area_slug: ?string, project_ids: array<int,int>, count: int}>
     */
    public function getZipMap(): array
    {
        return Cache::remember(self::CACHE_KEY, self::CACHE_TTL, function (): array {
            $allZips = app(\App\Services\HiveProjectsClient::class)->storedZips();
            if (empty($allZips)) {
                return [];
            }
            $allZips = array_flip($allZips);

            $zipCityMap = $this->loadZipCityMap();

            // city (lowercased) => area slug
            $areaBySlug = AreaServed::all(['city', 'slug'])
                ->mapWithKeys(fn ($a) => [mb_strtolower(trim($a->city)) => $a->slug])
                ->all();

            // Group published projects by normalized city name.
            $projectsByCity = [];
            $projects = Project::query()
                ->where('is_published', true)
                ->get(['id', 'location']);
            foreach ($projects as $p) {
                $city = trim(explode(',', (string) $p->location)[0] ?? '');
                if ($city === '') {
                    continue;
                }
                $cityKey = mb_strtolower($city);
                $projectsByCity[$cityKey][] = (int) $p->id;
            }

            // zip => [city, area_slug, project_ids[]]
            $zipMap = [];

            foreach (array_keys($allZips) as $zip) {
                $city = $zipCityMap[$zip] ?? 'Chicagoland';
                $cityKey = mb_strtolower($city);
                $projectIds = $projectsByCity[$cityKey] ?? [];

                $zipMap[$zip] = [
                    'city' => $city,
                    'area_slug' => $areaBySlug[$cityKey] ?? null,
                    'project_ids' => $projectIds,
                    'count' => count($projectIds),
                ];
            }

            ksort($zipMap);
            return $zipMap;
        });
    }

    /**
     * @return array<string, string>
     */
    protected function loadZipCityMap(): array
    {
        // Source of truth #1: hive_project_zip_counts table. The Hive sync
        // populates `city` per zip from the contractors source, so this is
        // available on every environment that has run `php artisan hive:sync`
        // (no separate seo:sync-zip-cities step required).
        $out = [];
        try {
            $rows = \App\Models\HiveProjectZipCount::query()
                ->whereNotNull('city')
                ->where('city', '!=', '')
                ->select('zip', 'city')
                ->distinct()
                ->get();
            foreach ($rows as $row) {
                $zip = preg_replace('/\D/', '', (string) $row->zip);
                $city = trim((string) $row->city);
                if (strlen((string) $zip) === 5 && $city !== '') {
                    $out[$zip] = $city;
                }
            }
        } catch (\Throwable) {
            // Table missing (fresh install) — fall through to JSON only.
        }

        // Source of truth #2 (override): storage/app/private/seo/zip-city-map.json.
        // Wins over the Hive value when both are present, so manual curation
        // via seo:sync-zip-cities can correct any odd city labels from Hive
        // (e.g. "Glenview Nas" -> "Glenview").
        $path = 'seo/zip-city-map.json';
        if (Storage::disk('local')->exists($path)) {
            $decoded = json_decode((string) Storage::disk('local')->get($path), true);
            if (is_array($decoded)) {
                foreach ($decoded as $zip => $city) {
                    $zip = preg_replace('/\D/', '', (string) $zip);
                    $city = trim((string) $city);
                    if (strlen((string) $zip) === 5 && $city !== '') {
                        $out[$zip] = $city;
                    }
                }
            }
        }

        return $out;
    }

    /**
     * @return array{city: string, area_slug: ?string, project_ids: array<int,int>, count: int}|null
     */
    public function find(string $zip): ?array
    {
        $zip = preg_replace('/\D/', '', $zip);
        $map = $this->getZipMap();
        return $map[$zip] ?? null;
    }

    /**
     * Convenience: list of ZIPs grouped by city.
     *
     * @return array<string, array<int, string>>
     */
    public function groupedByCity(): array
    {
        $grouped = [];
        foreach ($this->getZipMap() as $zip => $info) {
            $grouped[$info['city']][] = (string) $zip;
        }
        ksort($grouped);
        return $grouped;
    }

    public function flush(): void
    {
        Cache::forget(self::CACHE_KEY);
    }
}
