<?php

/**
 * Per-municipality building permit guide data, researched from official
 * village/city building-department pages, keyed by AreaServed slug.
 *
 * WHY THIS IS A CONFIG FILE: it used to live in
 * storage/app/private/permit-guides.json, which .gitignore excludes
 * (/storage/app). So it existed only on the developer machine and never
 * deployed — PermitGuideInfo::all() returned [] in production, every
 * /permits/{slug} hit abort_unless() and returned 404, and because the
 * sitemap is generated locally where the data DOES exist, all 10 URLs were
 * published to Google as live. Sibling clusters (config/trades.php,
 * config/insurance-claims.php) were always config files and never had this
 * problem.
 *
 * Entry shape (all strings unless noted):
 *   town, source_urls (string[]), permit_when_required, application_process,
 *   review_time, inspections, fees, contractor_registration,
 *   notable_quirks (string or string[]), researched_at
 */

return [
  'arlington-heights' => 
  [
    'town' => 'Arlington Heights',
    'source_urls' => 
    [
      0 => 'https://www.vah.com/government/permits___licenses_/index.php',
      1 => 'https://www.vah.com/government/departments/building___life_safety/index.php',
      2 => 'https://www.vah.com/government/permits___licenses_/permits.php',
      3 => 'https://www.vah.com/government/permits___licenses_/citizen_self_serve_portal.php',
      4 => 'https://www.vah.com/government/permits___licenses_/register_as_a_contractor.php',
      5 => 'https://www.vah.com/government/departments/building___life_safety/licensed_contractors.php',
      6 => 'https://www.vah.com/government/departments/building___life_safety/inspections.php',
      7 => 'https://www.vah.com/government/departments/planning___community_development/development___design_review_process_.php',
      8 => 'https://cms2.revize.com/revize/arlington/Government/Permits%20&%20Licenses/Checklists/Basement%20Remodel%20-%20Residential.pdf',
      9 => 'https://cms2.revize.com/revize/arlington/Government/Permits%20&%20Licenses/Building%20Permit%20Application%20Packets/Bathroom%20Remodel%20-%20Single%20Family.pdf',
      10 => 'https://cms2.revize.com/revize/arlington/Addition%20-%20Residential.pdf?t=202604070930460&t=202604070930460',
    ],
    'permit_when_required' => 'Kitchen, bath, and basement remodels all require a building permit, and "Addition - Residential" is a distinct permit type for residential additions. The Village publishes dedicated submittal checklists for Bathroom Remodel - Residential and Basement Remodel - Residential; the Building Permit Application also lists Kitchen Remodel, Basement Remodel, Bathroom Remodel, Single Family - Interior, Crawl Space Conversion, and Demolition (Interior) as distinct project types. The electrical permit instructions state "A permit must be obtained for all installations or alterations of electric equipment" and "before the work is started." A list of cosmetic-work exemptions (e.g., paint, flooring) is not published on the official site.',
    'application_process' => 'All applications go through the Village\'s Civic Access Portal (Tyler EnerGov self-service portal at vilofarlingtonheightsil-energovweb.tylerhost.net): "Anyone seeking a permit in the Village of Arlington Heights, will be required to utilize the Civic Access Portal," and all initial building permit submittals must be electronic. Applicants use the Apply tab, search by keyword, and must pick the correct permit type ("Selecting the wrong permit will result in your application being declined, and you will need to restart the process"). Required contacts (applicant, owner, and each trade contractor) must each have a portal account, and contractors must hold a valid Village contractor license. Typical remodel submittals require: Building Permit Application, Plumbing Permit Application (with Illinois 055 plumber license copy and a sealed/notarized Letter of Intent), Electrical Permit Application (with electrician registration copy), Contractor List (if more than one contractor), Tax Assessor Supplemental Information form, fully dimensioned scaled plans (architect/engineer seal not required for bath/basement remodels), and the contractor\'s proposal with scope and cost. Plans must be uploaded as a single compiled attachment. Additions also need a current plat of survey and a Construction Fence/Silt Fence Acknowledgment. Homeowners acting as their own general contractor must submit the "Homeowner as General Contractor" form. Building & Life Safety Dept: 847-368-5560, building@vah.com, 33 S. Arlington Heights Rd.',
    'review_time' => 'Per the current (April 2026) residential Addition packet: "Once placed into review, the typical time frame allotted for initial review or revisions is 10 business days. Not all reviews require the full amount of time allotted." Older remodel checklists likewise say "Please allow 10 working days for the plan review. Each revision or re-submittal can take an additional 10 working days." After approval and payment, plans and the permit placard are emailed within 24 hours (per the remodel checklists). Contractor registrations are reviewed and issued in 24-48 hours.',
    'inspections' => 'Inspections are required and are scheduled through the Civic Access Portal. Requests must be made at least 24 hours in advance (the permits page states 48 hours for final inspections); "All inspection requests for the following business day must be submitted before 4:00 pm"; same-day inspections are not offered; inspections are scheduled for a morning or afternoon window. "All inspections require a hard copy of the approved stamped documents on site" (approved plans and permit placard must be printed and available). For additions/ground-disturbing work, silt fence and construction fence must be installed and inspected before work starts, with a fence-removal inspection at completion (interior remodeling with no exterior exposure is listed as work where these fences are not required in practice). Electrical work must pass inspection before being energized. A published step-by-step inspection sequence (rough/insulation/final) for interior remodels is not published on the pages reviewed.',
    'fees' => 'Building permit fees: not published as a schedule. The Village states "Fees are not pre-set based on project type" — the detailed permit cost is shown in the approval/pick-up notification; additional fees may be added once all reviews are completed. An electrical inspection fee is based on the apparatus listed on the application and must be paid before the permit is issued; the plumbing permit fee is likewise based on the fixtures listed on the application. Contractor registration: $130 annual fee ($65 half-year starting in July); electrical, plumbing, and alarm contractors are exempt from the $130 fee.',
    'contractor_registration' => 'Yes — Village contractor licensing/registration is mandatory. Registration is submitted online through the Civic Access Portal (create account, Apply, select trade); allow 24-48 hours for review and issuance. Fee is $130/year for most trades ($65 half-year from July); all registrations expire December 31 each calendar year. The Village of Arlington Heights contractor license number must be listed on permit applications, and "All Contractors must be licensed prior to the issuance of the permit" with the license valid through the project\'s duration; the GC is responsible for ensuring all subs are licensed locally and at state level. General contractors do not need a certificate of insurance or surety bond; surety bonds are required only for demolition/excavation contractors ($20,000) and sewer contractors ($10,000). Plumbers must hold the Illinois 055 license and submit a Letter of Intent with every plumbing permit; electricians must submit a copy of their registration with each application. The Village publishes a downloadable Licensed Contractors list (PDF).',
    'notable_quirks' => '1) Design review: the Planning & Community Development Department reviews building permit applications for compliance with the Village\'s "standards for architecture and aesthetics"; single-family Design Commission applications are reviewed case-by-case to determine administrative staff approval vs. formal Design Commission approval (factors: location, scale, context, design), and "All projects require building permit approval after design approval is obtained" — relevant mainly to exterior work like additions, not stated to apply to interior remodels. 2) Choosing the wrong permit type in the portal gets the application declined and you must restart. 3) Plans must be one compiled PDF attachment, and a printed hard copy of stamped approved documents is required on site. 4) A Tax Assessor Supplemental Information form (square footage/bath/bedroom counts) is required with remodel applications. 5) Historic districts: no historic-district permit requirements are published on the official site (not published). 6) Owner must generally be listed as a contact on the permit and needs their own portal account.',
    'researched_at' => '2026-07-14',
  ],
  'barrington' => 
  [
    'town' => 'Barrington',
    'source_urls' => 
    [
      0 => 'https://www.barrington-il.gov/government/departments/development-services/permits-inspections/',
      1 => 'https://www.barrington-il.gov/government/departments/development-services/dsfaq/',
      2 => 'https://www.barrington-il.gov/government/departments/development-services/forms/',
      3 => 'https://www.barrington-il.gov/government/departments/development-services/historic-district/',
      4 => 'https://www.barrington-il.gov/wp-content/uploads/2022/11/Building20Permit20Fee20Schedule2018-1231.pdf',
      5 => 'https://www.barrington-il.gov/wp-content/uploads/2023/05/Contractors-Registration-App.pdf',
    ],
    'permit_when_required' => 'Permits ARE required for interior alterations including kitchen and bath remodels, finished basements, and additions, as well as for one-for-one replacements ("driveways, roofs, fences, water heaters, etc.") to ensure "compliance with all current building and zoning codes." The permits page lists interior alterations, additions, decks, garages, pools, fences, driveways, HVAC, water heaters, generators, solar, roofing, siding, windows and doors as permit categories. The FAQ notes that shingle/siding/window replacement, driveways, patios, sidewalks, small decks, finished basements, and kitchen/bath remodels "typically don\'t require an architect" unless bearing walls or foundations are modified — but they still require permits. The site does not publish an explicit list of exempt cosmetic work (painting/flooring are simply not listed as requiring permits); exact cosmetic exemptions: not published on the pages read. Adopted codes: 2018 ICC set (building, residential, fuel gas, mechanical, fire, property maintenance), 2017 NEC, Illinois Energy Conservation Code (2021 IECC), Illinois State Plumbing Code.',
    'application_process' => 'Online via the "Village of Barrington Online Permit and Contractor Registration Portal" (SmartGov: vlg-barrington-il.smartgovcommunity.com/Public/Home). Interior alterations require a detailed written project description and detailed construction plans. Common submittals: completed application, plat of survey, scaled site plan with dimensions/setbacks, and material/equipment specifications. New construction and additions must be submitted as 2 paper copies (not online) with stamped architectural/engineering plans, soil boring information with seasonally adjusted water-table data, water service review form, and a Watershed Development Permit. Permit fees are paid online after approval, then the permit is issued. Development Services: (847) 304-3460.',
    'review_time' => 'Approximately 8-10 business days for a standard permit to be "reviewed, processed and issued"; the Village states new construction, large remodels and/or additions and commercial projects "will likely exceed this estimated time frame." A quick-review expedited process exists for roofs, water heater replacements, and door/window replacement permits (specific expedited turnaround not published).',
    'inspections' => 'Inspections occur "at various stages of a project to verify the code standards are being followed" — a full inspection sequence for remodels is not published. Scheduling: call (847) 304-3460 at least 24 hours in advance. Approved permit plans must be available on-site and the permit placard displayed in a visible location on-site, or inspections will not be conducted. For pre-pour inspections, property corner pins must be located and clearly staked, or the inspection is refused and a $50.00 reinspection fee may apply. Fee schedule lists Reinspection Fee $75.00 and Minimum Inspection Fee $50.00.',
    'fees' => 'Construction Permit Fee Schedule (effective 7/1/2018): Detached single-family alterations/additions/new construction — habitable space $0.95/sqft, non-habitable $0.60/sqft, conversion of space $0.60/sqft, minimum permit fee $55.00; attached single-family habitable $1.00/sqft. Trade fees for alterations/additions: Electrical $0.12/sqft ($55 min), Plumbing $0.12/sqft ($55 min), HVAC $0.12/sqft ($55 min); electrical service $100/panel; new HVAC units $100/unit; water heater, roofing, siding, window replacement, deck, fence, patio, driveway each $55 permit + $50 plan review = $105 total. Plan review fees by gross floor area: up to 1,000 sqft $100; 1,001-3,000 sqft $300; 3,001-5,000 sqft $500; over 5,000 sqft $800 + $100/hr over two hours; all other plan reviews $50 minimum. Reinspection $75; permit extension $100; single-family certificate of occupancy $50/unit; starting work without a permit or stop-work order: 50% of total permit fees or $750, whichever is less. Note on schedule: total permit cost varies with project scale and number of inspections.',
    'contractor_registration' => 'Required: "All contractors and subcontractors associated with your permit must be registered with the Village. Your permit will not be issued until all contractors have completed the required contractor registration." Registration is done via the same SmartGov portal or the paper Contractor\'s Registration Application; valid one (1) year from date of payment. The 2023 application form states Fee = $100.00 per contractor, with plumbing and alarm contractors exempt from the fee (the older 2018 fee schedule shows $75.00 / $50.00 after July 1 — the documents conflict; the newer form says $100). License documentation required by trade: plumbing — copy of state plumbing license; roofing — copy of state roofing license; electrical — copy of a municipal electrical license; general contractor — certificate of insurance.',
    'notable_quirks' => '1) Historic Overlay District: all exterior modifications to contributing AND non-contributing structures require Architectural Review Commission approval via a Certificate of Appropriateness in addition to a building permit; the ARC process "generally takes 60-90 days" (preliminary + final review meetings); no fee to apply for a COA; smaller projects (replacement roofs/windows) may be approved administratively by the Zoning Official if no historic/original materials are removed. Interior remodels are exempt — "The Architectural Review Commission has no jurisdiction on the interior of historic properties, just the exterior." 2) Bonds: $1,000 Right-of-Way cash deposit for any work in the public right-of-way; Road/Performance cash bond of $0.50/sqft (waived if calculated amount is under $250). 3) Additions/new construction plans must comply with the Illinois Electric Vehicle Charging Act (Public Act 103-0053). 4) Additions require watershed development permit and soil boring data. Contact for historic district: Jennifer Tennant, Director of Development Services, (847) 304-3462.',
    'researched_at' => '2026-07-14',
  ],
  'glenview' => 
  [
    'town' => 'Glenview',
    'source_urls' => 
    [
      0 => 'https://www.glenview.il.us/651/Development-Center-Building-Permits',
      1 => 'https://www.glenview.il.us/739/Residential-Inspections',
      2 => 'https://www.glenview.il.us/659/Contractor-Registration',
      3 => 'https://www.glenview.il.us/DocumentCenter/View/3008/this-chart-PDF',
      4 => 'https://www.glenview.il.us/593/Planning-Division',
    ],
    'permit_when_required' => 'Per the Development Center / Building Permits page, a permit is required for "addition, remodeling, altering, or construction of any structure," including electrical, mechanical, and plumbing work, roofing (50%+ replacement), siding, decks, sheds, detached garages, and pools. The page states no permit is needed for interior painting, flooring, cabinet installation, or HVAC/water-heater replacement with the same specifications. The Village\'s permit-submittal chart lists "Single Family Remodeling" as its own permit type requiring a completed application, architectural drawings, plat of survey, and equipment specifications; "Single Family Addition" additionally requires site plan, site development plan, tree preservation plan, engineering grading plan, equipment specifications, and energy conservation information.',
    'application_process' => 'Apply through the Village\'s online permit portal at glenview.onlama.com/Apply.aspx (LAMA portal), or submit a printed permit application (Permit Application PDF) in person at the Development Center inside Village Hall, 2500 East Lake Avenue, Glenview (hours 8:30 am–4:30 pm, Mon–Fri; phone (847) 904-4330). If contractors change after a permit exists, a Change of Contractors form must be filed.',
    'review_time' => 'Same-Day Review (SDR): eligible applications received before 1 pm are reviewed the same business day; applications submitted after 1 pm are reviewed the next business day, and complicated applications may require additional review time. Standard reviews are typically completed within 10 business days; for complex permits requiring commission/agency approval, "initial traditional permit reviews are typically available within two weeks."',
    'inspections' => 'Every permit requires inspection. Residential inspection categories published: Building (site development — silt fence/construction fence/tree protection/signage — footings, foundation, framing, insulation, through Final Occupancy); Plumbing (underground, rough, final); HVAC (rough duct inspection per unit or story, final); Electrical (slab wiring, rough, service, final, generators); and Engineering (utilities, detention, water/storm/sanitary, sidewalks, grading, landscaping). Schedule by calling (847) 904-4320. "Additional inspections may be necessary pending job site conditions." Reinspection fees: not published.',
    'fees' => 'Dollar amounts not published on the permit pages — the site directs readers to Chapter 30 of the Glenview Municipal Code, and fees are calculated after plan approval. Published incentive: 25% discount on building and plan-review permit fees for single-family home improvement projects (including room additions and interior remodeling) for applications filed December 1–February 28. Contractor registration fee: $50 for general and demolition contractors.',
    'contractor_registration' => 'Yes for some trades. General and demolition contractors must register with the Village: $50 fee, $25,000 bond, certificate of insurance, and proof of workers\' compensation. Roofers (state roofing license copy), electricians (license copy), and plumbers ("Copy of 055 State License and Letter of Intent") provide credentials with no Village fee/bond. "Types of contractors not listed... do not require registration with the Village" (other subcontractors exempt). Registration is online or by printed form.',
    'notable_quirks' => '(1) Winter incentive: 25% off building/plan-review fees for single-family remodel/addition applications filed Dec 1–Feb 28. (2) $25,000 bond required for general/demolition contractors. (3) The Glenview Development Commission\'s published design-review scope is commercial appearance (buildings, landscaping, signage) — no residential design review is published for typical remodels. (4) Glenview publishes a Historic Preservation Handbook and Landmark Designation Application, so landmarked properties may carry extra requirements; specific historic-district rules for single-family remodels are not published on the pages read. (5) Single-family additions require a tree preservation plan, engineering grading plan, and energy conservation information; remodel permits require equipment specifications. (6) Same-Day Review program (before 1 pm) is unusual and useful for simple permits.',
    'researched_at' => '2026-07-14',
  ],
  'highland-park' => 
  [
    'town' => 'Highland Park',
    'source_urls' => 
    [
      0 => 'https://www.cityhpil.com/government/city_departments/community_development/building/permit_applications_requirements.php',
      1 => 'https://www.cityhpil.com/government/city_departments/community_development/building/faqs.php',
      2 => 'https://www.cityhpil.com/government/city_departments/community_development/building/submittal_requirements.php',
      3 => 'https://www.cityhpil.com/government/city_departments/community_development/building/inspections.php',
      4 => 'https://www.cityhpil.com/government/city_departments/community_development/building/contractor_requirements.php',
      5 => 'https://www.cityhpil.com/business/licenses_registration_and_permits/city_licenses_permits.php',
      6 => 'https://www.cityhpil.com/business/licenses_registration_and_permits/permits_licenses_fee_schedule.php',
      7 => 'https://www.cityhpil.com/government/city_departments/finance/city_finances/annual_fee_resolution.php',
      8 => 'https://www.cityhpil.com/government/advisory_groups_boards_commissions/historic_preservation_commission/applying_for_a_certificate_of_appropriateness.php',
    ],
    'permit_when_required' => 'Per the Building Division FAQs, "Permits are required for most construction projects"; exemptions are found in the City\'s adopted building code amendments (not enumerated on the website). The Permit Administration page lists dedicated permit categories including "Single Family Interior Alterations/Remodel," "Residential Addition," "Multi-Family (Condo) Interior Alteration," and separate plumbing requirements — so kitchen, bath, basement, and addition remodels are permitted project types. The site does NOT publish an explicit list of exempt cosmetic work (paint, flooring, etc.); it directs uncertain applicants to building@cityhpil.com / 847.432.0808. Cosmetic-work exemption specifics: not published.',
    'application_process' => 'All permit applications and supporting materials are submitted online via the City\'s "Civic Access Portal" (selfservice.cityhpil.com, an EnerGov self-service system; users must re-register after system upgrades). All applications and supporting documentation must be submitted at the same time — incomplete submissions are not accepted. Every permit requires a signed Property Owner Authorization Form. Project-specific document lists (e.g., Single Family Interior Alterations/Remodel, Residential Addition) are on the Submittal Requirements page. After plan review approval the City emails an invoice; once fees are paid the applicant receives the permit placard and approved drawings. Building Division: 1150 Half Day Rd, 2nd Floor, 847.432.0808, building@cityhpil.com.',
    'review_time' => 'Published on the Building Division FAQs: plan review "typically lasts 5 to 15 business days (depending on the type of project and information provided)" once all required documents have been received.',
    'inspections' => 'Inspections are requested through the Civic Access Portal (\'Request Inspection\' on the permit), by email to buildinginspections@cityhpil.com (include address, permit number, inspection type, contact, and AM 8am-12pm or PM 12pm-3pm preference), or by phone 847.432.0808. Requests received by 2:30pm can often be scheduled next business day. The site references a "Required Inspections Matrix" document (examples cited: electrical, framing, plumbing) but does not list the full residential sequence on the page. Rules published: a printed copy of approved plans must be on the job at all inspections; the contractor shall be available for inspection; the plumber must attend plumbing inspections; as of December 1, 2025 plumbing inspections are only available Tuesday-Thursday; remote photo submissions accepted only if approved by the inspector. Re-inspection fees: not published.',
    'fees' => 'Not published as specific amounts. The Permits & Licenses Fee Schedule page lists "Building Permit — Varies," and the Permit Administration page states permit fees are calculated according to the City\'s Annual Fee Resolution upon completion of review. The current fee amounts live in the "2026 Annual Fee Resolution" PDF on the Finance page; no residential remodel/addition dollar figures are published on the web pages themselves.',
    'contractor_registration' => 'Yes — per the City Licenses & Permits page, "General contractors doing construction in Highland Park are required to have a license" (obtained through the Building Division, 847.432.0808). The Contractor Requirements page provides a General Contractor License Application (v3.0), a Change of Contractor form (required if the contractor changes mid-project), a "Bond Language" requirement document, a Felony Statement disclosure, and the Property Owner Authorization Form. A "Homeowner as General Contractor Agreement" form is also provided. Specific license fees, bond amounts, and insurance limits are only in the downloadable documents, not published on the web pages read.',
    'notable_quirks' => '1) Historic preservation: 136 regulated historic structures (80 individual landmarks plus local historic districts). Substantial EXTERIOR alterations to regulated structures require a Certificate of Appropriateness from the Historic Preservation Commission — even work not visible from the public right-of-way — applied for via the Civic Access Portal ("Certificate of Appropriateness (HPC)") at least 31 days before the monthly HPC meeting. Explicitly stated: "Interior alterations do not require a COA," so interior kitchen/bath/basement remodels are exempt from HPC review. 2) A contractor bond is required per the "Bond Language" requirement document (amount not published on the pages read). 3) All-at-once submittal rule: incomplete Civic Access applications are rejected outright. 4) Construction hours: outdoor construction only 7am-7pm Mon-Fri, 9am-5pm Saturday, none on Sundays/holidays (residents working on their own home are exempt from the prohibition). 5) Community Development is at 1150 Half Day Rd, 2nd Floor; walk-ins are closed on Mondays, and the office is open Tue-Fri 7:30am-4pm.',
    'researched_at' => '2026-07-14',
  ],
  'mount-prospect' => 
  [
    'town' => 'Mount Prospect',
    'source_urls' => 
    [
      0 => 'https://www.mountprospect.org/business/licenses-and-permits/building-permit-application-and-inspections',
      1 => 'https://www.mountprospect.org/departments/community-development/building-permit-application-and-inspections/residential-fee-code',
      2 => 'https://www.mountprospect.org/departments/community-development/contractor-licensing',
      3 => 'https://www.mountprospect.org/departments/community-development/faqs-frequently-asked-questions',
      4 => 'https://www.mountprospect.org/home/showpublisheddocument/3571/636282812647200000',
      5 => 'https://www.mountprospect.org/home/showpublisheddocument/21166/639017561916600000',
      6 => 'https://www.mountprospect.org/home/showpublisheddocument/21158/639017561898230000',
      7 => 'https://www.mountprospect.org/home/showpublisheddocument/21234/639026170946370000',
      8 => 'https://www.citizenserve.com/mpportal',
    ],
    'permit_when_required' => 'Per the Village FAQ: "new buildings, additions to existing structures, renovations, demolitions, and temporary buildings usually require building permits and inspections." Less obvious projects that may require a permit include swimming pools, decks, fences, and roofs, plus "some tasks that involve electrical, plumbing, heating, ventilation and air conditioning systems, and fireplaces." The Village\'s published rule of thumb: "if it involves adding, moving, or exposing water, gas, electricity or walls, or it involves your property lines, it is going to need a permit!" The Village publishes permit supplements specifically for Kitchen remodels, Bathroom remodels, Basement Buildouts, plus decks, egress windows, HVAC, roofs, fences, sheds, generators, pools, etc. — all permit-required scopes. A list of exempt cosmetic work (paint, flooring, etc.) is not published on the pages read. FAQ also notes homeowners must apply "whether a professional or a do-it-yourselfer does the job."',
    'application_process' => 'Online via the Village\'s Citizenserve Online Portal (linked as "Online Portal" from the Building Permit page; www.citizenserve.com/mpportal, also reachable via www.mountprospect.org/permits) — upload required documents; or in person at the Building Division, 2nd floor of Village Hall, Community Development, 50 S. Emerson St. Required with the application (per kitchen/bathroom/basement supplements): application completed and signed by the homeowner; signed copy of the contractor\'s estimate (or a detailed written scope/material list if the homeowner does the work); a detailed dimensioned plan (hand-drawn acceptable; cabinet-maker layout acceptable for kitchens); electrical devices/circuits marked on the plan plus a photo of the open electrical panel; plumbing isometric drawing for basement plumbing work. Removal of any wall requires architecturally stamped plans or a stamped architect letter stating whether the wall is load-bearing (and the required support if it is); "Structural changes require architectural stamped plans." Main permit page: "some residential projects will require an Architect or a Licensed Professional." A free pre-submittal meeting can be scheduled at (847) 870-5675 or permit@mountprospect.org. Building Division hours: Mon-Fri 7:30 a.m.-5 p.m.',
    'review_time' => 'not published (no plan-review turnaround time appears on the Building Permit, Fee Code, or FAQ pages read)',
    'inspections' => 'Permit applicant is responsible for scheduling ALL inspections; minimum 24 hours advance notice (48+ hours during construction season) at (847) 870-5675 option 2. Published "Residential Required Inspections and Testing" list (not exhaustive; scope-dependent): soils report (new construction/demolition/unusual sites); steel test reports; pre-pour inspections (footings, foundation walls, slabs, flatwork, driveways); concrete/steel test reports; water and sewer inspection prior to backfill; backfill inspection (incl. damp-proofing and drain tile); plumbing stack test and gas pressure test; rough inspection after all structural/mechanical/electrical/plumbing/fireplace/fire-suppression work but before walls are covered; fire suppression hydro test; electric service inspection before energizing; A/C inspection; insulation inspection after fire stopping; masonry inspection; and final inspections (roof, HVAC, plumbing and water heaters, structural, site concrete, fire suppression/fire alarm acceptance test, zoning, engineering, sewer & water service, etc.). Basement projects with plumbing also require an end-of-project water pressure test; WaterSense fixture labels are checked at final inspection (Village Ordinance 6209). FAQ: inspections must be scheduled at least 24 hours ahead and failed items get a written correction list.',
    'fees' => 'Published flat-fee tiers on the Residential Fee Code page (flat fees replace construction-cost-based fees): $75 each for fences, roofs and sheds; $200 (with $100 refundable) for decks, concrete pavement, and simple mechanical, electrical or plumbing projects; $500 ($150 refundable) for kitchen remodels or to finish a basement; $750 ($250 refundable) for full interior remodels or fire restorations. Additions and new construction: $2 per square foot of new construction, minimum fee $750, plus a $350 refundable escrow; interior remodel associated with an addition: $1 per square foot. Contractor license fee: $200.',
    'contractor_registration' => 'Yes — Village contractor licensing is required for "all Contractors that are general or specialized trade"; a company that is the only contractor on a project or oversees multiple trades is considered a General Contractor. Licenses are applied for or renewed electronically through the Online Portal (Citizenserve); fee is $200.00 and licenses are valid one year from date of issuance. State-licensed roofers, fire alarm, sprinkler, plumbing, and electrical contractors must submit their required state licenses/registrations and complete the Village application. Printed applications are accepted in person at the Building Division (cash, check, or credit card).',
    'notable_quirks' => '(1) Refundable escrow built into permit fees ($100-$350 depending on tier) — functions like a completion deposit returned after the project. (2) Conduit requirement: all new electrical wiring must be in conduit (non-metallic sheathed cable prohibited; BX not allowed in basement buildouts) — a Chicago-area quirk that affects remodel pricing. (3) Wall removal always needs an architect\'s stamped plans or stamped load-bearing determination letter. (4) Homeowner-performed plumbing triggers an Illinois State Plumbing Code restriction on selling the home for 6 months from permit closing. (5) Permit card, approved plans, and Tree Protection Plan must be displayed on the job site. (6) Free pre-submittal meetings offered. (7) Fire-sprinkler incentive options approved by the Village Board for single-family construction projects. (8) Construction hours: 7 a.m.-7 p.m., Monday-Sunday. (9) Codes: 2021 IBC/IRC, 2021 IMC/IFGC, 2020 NEC, IL State Plumbing, IL Energy Conservation and IL Accessibility codes with local amendments (adopted Feb 15, 2022). No historic district, design review board, or bond requirement for residential remodels is published on the pages read. Note: content was read from Wayback Machine archives (Mar-Apr 2026) of the official mountprospect.org pages because the live site blocks automated access.',
    'researched_at' => '2026-07-14',
  ],
  'northbrook' => 
  [
    'town' => 'Northbrook',
    'source_urls' => 
    [
      0 => 'https://www.northbrook.il.us/1069/Building-Permits',
      1 => 'https://www.northbrook.il.us/505/Single-Family-Residence-Permits',
      2 => 'https://www.northbrook.il.us/518/Single-Family-Alterations---Interior',
      3 => 'https://www.northbrook.il.us/515/Single-Family-Addition',
      4 => 'https://northbrook.il.us/758/Licenses-Permits',
      5 => 'https://www.northbrook.il.us/746/Information-for-Contractors',
      6 => 'https://northbrook.il.us/747/Building-Inspections',
      7 => 'https://www.northbrook.il.us/m/faq?cat=24',
      8 => 'https://www.northbrook.il.us/470/Village-Green-Design-Review-Applications',
    ],
    'permit_when_required' => 'Interior remodels: "An alteration permit is required when any interior walls or structural elements are to be changed" (Single-Unit or Individual Multi-Unit Residential Interior Alteration permit). The Village also issues distinct residential permit types for Addition (increase in floor area), Major Renovation (over 115% increase in floor area of an existing residence), Interior Alteration, and Exterior Alteration (change to exterior or roof). Cosmetic work explicitly exempt from permits per the Licenses & Permits page: residential re-roofing (shingle/shake replacement), residential/commercial painting, residential drywall repair, residential floor covering installation/removal (carpet, tile, laminate), residential low-voltage installations (security, cable TV, phone), residential siding installation, soffit replacement, stucco installation, asphalt sealcoating (contractor license still required), like-for-like electrical fixture replacements, like-for-like plumbing fixture replacements, and prefabricated sheds up to 80 sq ft (zoning compliance still required).',
    'application_process' => 'Submittal is by email: "Please email all submittal documentation / drawings to Permits@Northbrook.il.us" (Development and Planning Services, 1225 Cedar Lane, 847-664-4050). Credit-card payment is accepted on fees up to $15,000. Required documents for an interior alteration packet include: Permit Application, Building Site and Utility Data Worksheet, Water Service and Meter Worksheet, Tree Protection Agreement, Fire Protection Letter of Understanding, Contractor of Record documentation, and plumbing contractor credentials (State 055 registration plus a notarized/sealed plumbing letter of intent) if applicable. Additions also require a Zoning Worksheet – Residential, separate architectural and civil engineering drawings, and a sealed to-scale survey. The Village recommends reviewing its Residential Plan Review Checklist and "Common Residential Plan Submission Mistakes" before submitting. Properties in the Mission Brook Sanitary District need a separate sewer application.',
    'review_time' => 'Published on the Village FAQ: over-the-counter permits (sewer repair, electrical only, etc.) up to 24 hours; Small Projects (decks, sheds, basements, kitchens/baths, parking lot resurfacing, etc.) up to 10 business days; Large Single Family Residential projects (additions or large-scale remodeling) up to 15 business days; New Single Family Residence or large commercial remodeling up to 20 business days; re-submittals from plan-review comments generally 10 business days.',
    'inspections' => '"The Development and Planning Services Department requires mandatory inspections for permitted work within the Village." Per the FAQ: "All jobs will require a final inspection, however most jobs will require additional inspections" at various construction stages, and work is inspected before it is covered up. Scheduling: call the Permit Coordinator Desk at 847-664-4050 a minimum of 48 hours in advance with the property address. A re-inspection fee is charged for each failed inspection or an inspection not canceled at least 4 hours prior. A Spot/Location Survey Approval step applies during construction of additions. A specific named inspection list (e.g., footing, framing, insulation) is not published.',
    'fees' => 'Interior Alteration: "Building Construction and Inspection Fee - $3.00 per square foot of floor area with a minimum of $280," due at permit issuance; additional fees may apply upon approval. Single-Family Addition: $3.00 per sq ft of floor area (due at permit pick-up) plus a $250 Permit Application Deposit requested after the application is accepted, with additional fees possible at approval. The FAQ states every project is unique and directs applicants to per-project-type fee/deposit information; a consolidated fee schedule amount for every remodel type is not published on the pages read. Contractor license fees: General $100; Electrical, Sewer, Pavement, Sealcoat $70 each; Plumbing and Landscape no fee.',
    'contractor_registration' => 'Yes. "General Contractors, Concrete / Paving Contractors, Electrical Contractors, Plumbing Contractors and Sewer Contractors are required to have valid licenses" to work in the Village, and "plumbing, electrical, concrete, and general construction work must be performed under the direct supervision of contractors licensed by the Village of Northbrook for that particular trade." License is good for one year from application date (annual renewal). Fees: General Contractor $100; Electrical/Sewer/Pavement/Sealcoat $70; Plumbing and Landscape no fee. Electrical contractors must submit a valid electrician\'s registration; plumbing contractors must submit their State of Illinois Plumbing Contractor Registration (055). A Village license is NOT required for HVAC, Fire Protection, Fence, or Sign contractors.',
    'notable_quirks' => '1) "Major Renovation" is a distinct permit category triggered when a project increases floor area of an existing residence by over 115%. 2) Additions require a $250 permit application deposit and a sealed to-scale survey, with separate (non-integrated) architectural and civil engineering drawings; civil requirements differ for projects under vs over 400 sq ft, and a Spot/Location Survey Approval is required during construction. 3) A Tree Protection Agreement is part of the interior-alteration packet, and tree removal needs its own permit. 4) A Fire Protection Letter of Understanding is required in residential permit packets. 5) Village Green Overlay District (VG-O, downtown): new development or redevelopment impacting 10,000–50,000 sq ft of gross floor area or site area requires Design Review through the Zoning Board of Appeals (Zoning Code Art. 9, Sec. 9-104) — typical single-family interior remodels are not stated to be affected. 6) Properties within the Mission Brook Sanitary District need a separate sewer application. 7) Sealcoating contractors must sign an affidavit prohibiting coal-tar pavement products, and even permit-exempt sealcoat work requires a licensed contractor. 8) No historic district requirements are published on the pages read.',
    'researched_at' => '2026-07-14',
  ],
  'palatine' => 
  [
    'town' => 'Palatine',
    'source_urls' => 
    [
      0 => 'https://www.palatine.il.us/621/When-a-Building-Permit-is-Required',
      1 => 'https://www.palatine.il.us/620/Standard-Building-Permits',
      2 => 'https://www.palatine.il.us/191/Building-Permit-Inspections',
      3 => 'https://www.palatine.il.us/faq.aspx?TID=19',
      4 => 'https://www.palatine.il.us/213/Building-Permit-FAQs',
      5 => 'https://www.palatine.il.us/609/Express-Building-Permits',
      6 => 'https://www.palatine.il.us/210/Contractor-Registration',
      7 => 'https://www.palatine.il.us/219/Inspections',
      8 => 'https://www.palatine.il.us/DocumentCenter/View/738/Residential-Submittal-Requirements-PDF',
      9 => 'https://www.palatine.il.us/DocumentCenter/View/166/Inspection-Requirements---Residential-PDF',
      10 => 'https://www.palatine.il.us/Archive/ViewFile/Item/1618',
      11 => 'https://www.palatine.il.us/868/Historic-Palatine',
    ],
    'permit_when_required' => 'Per the Village\'s "When a Building Permit is Required" page, permits ARE required for: remodeling a kitchen or bathroom; finishing or remodeling a basement; adding rooms/room additions; adding or altering the electrical system; building or replacing a deck, shed, or roof; replacing or installing an air conditioning unit, heating unit, or water heater. Permits are NOT required for cosmetic work: painting exterior or interior walls; installing new flooring; replacing a window or door with the same size/type unit within the same framed opening; replacing a faucet. The Village notes the list is not all-inclusive and to contact the Building Department (847-359-9042) with specific questions. The FAQ adds that new buildings, additions, renovations, demolitions, temporary buildings, pools, decks, fences, and electrical/plumbing/HVAC/fireplace work usually require permits. Two permit tracks exist: Express permits (a fixed list of 16 small detached single-family project types such as AC/furnace/water heater replacement, roof tear-off, decks, fences, driveways — valid 90 days from issuance) and Standard permits (everything else, including kitchen/bath/basement remodels and additions).',
    'application_process' => '100% online — "All permit applications must be submitted on-line through the Citizen Self Service (CSS) portal" (https://citizen.palatine.il.us, an EnerGov self-service system; paper applications are not accepted). Registration on CSS is required; the Village publishes Step-by-Step CSS Registration and Application guides. For new construction, additions, and remodels the Residential Submittal Requirements document requires: (A) digital building permit application + copy of signed contract, (B) Building Permit Contractor List form (contractors must be registered and bonded with the Village; may be provided after application but before issuance), (C) current plat of survey (NOT required for interior-only work that adds no lot coverage), (D) plat of survey affidavit where an older plat is used, (E) working drawings min 18"x24" (floor plans at 1/4"=1\', electrical, HVAC, plumbing isometrics, cross-sections; remodels/additions must show existing structure and distinguish new from existing with dashed lines for removals), (F) manufacturer specs for HVAC/fireplaces (ACCA Manual J/S sizing), (G) shop drawings for trusses/sprinklers, (H) ResCheck energy report if exterior glazing exceeds 15%. Incomplete submittals are not accepted. Pre-submittal meetings are no longer required but available on request (typically scheduled within one week). Review is against the 2021 IRC, 2021 IMC, 2021 IFGC, 2021 IECC with Illinois amendments, 2021 ISPSC, 2020 NEC (with amendments), and Illinois Plumbing Code.',
    'review_time' => 'Published goals on the Building Permits & Inspections page: Express permits — "Our goal is to have these reviewed in 5 business days"; Standard permits — "Our goal is to have these reviewed in 10-15 business days." Review does not begin until all required materials are submitted. Certificate of Occupancy/Compliance processing may take up to 5 business days after final approvals.',
    'inspections' => 'The Residential Inspection Requirements document lists the individual required inspections; the specific list for each permit prints on the permit card and shows in the CSS portal. Documented inspection types relevant to remodels/additions: underground/under-slab plumbing (before concealment); rough plumbing (underground + above-ground, with stack test), rough mechanical, and rough electrical — all trade roughs must be approved BEFORE the rough frame inspection; rough frame (all framing inspected before covering, including fire-stopping); insulation (before concealment); house wrap (additions, after windows/roofing, before exterior finishes); concrete pre-pour (footing and foundation wall separately); foundation wall/draintile/waterproofing before backfill; final frame, roof, plumbing, mechanical, and electrical inspections after all work is complete. Energy testing: duct leakage test per 2021 IECC with IL amendments; blower door test for additions/alterations/renovations as required by the 2021 IECC (mandatory for new homes, BPI-certified tester) — no CO issued until passing reports are received. Additions/new homes also require spot survey (before rough), topographical survey and final grade inspection, and soils reports on teardown sites. Scheduling: through the CSS portal with minimum 24-hour notice; slots Mon-Fri 8-10 a.m., 10 a.m.-12 p.m., 1-3 p.m. (plumbing inspections Mondays and Thursdays only). Approved job-copy plans must be on site or the inspection is failed. Project closes with a Certificate of Occupancy or Certificate of Compliance, which the permit holder must request.',
    'fees' => 'Published in the Village of Palatine Fee Schedule Supplement to the Code of Ordinances (CY 2024 edition, Village website archive). Key residential figures (CY 2024): Plan examination for single-family detached dwellings, additions, alterations, remodeling — $54 for valuation of $5,000 or less, plus $5 per $1,000 of valuation above $5,001. Building permit fee — $54 for $5,000 or less, plus $16 per $1,000 above $5,001. Minimum inspection fee $72. Trade inspection fees: plumbing fixtures $72 (up to 3), $143 (4-6), +$18/fixture beyond 6; residential electrical $72 (≤250 sq ft), +$143 (251-1,000 sq ft), +$36 per additional 1,000 sq ft; HVAC $72 (≤250 sq ft) +$143 (251-10,000 sq ft); carpentry/framing/insulation $72 (≤500 sq ft) +$215 (501-1,000 sq ft), +$36 per 1,000 sq ft up to 10,000. Re-inspection fee $72; cancellation fee $86. Certificate of Occupancy $68 per unit; permit extension 10% of permit fee ($73 min/$219 max residential). Flat express-type fees: roof tear-off/re-roof $99, deck $99, fence $74, shed $74, driveway $99, patio/private walk $99, HVAC replacement $99, sewer repair $99, electric service revision $99. Contractor annual registration: general contractor $269, all other contractors $67 (Sec. 11-473). Note: figures are the published CY 2024 schedule; confirm current-year amounts with the Village before relying on them.',
    'contractor_registration' => 'Yes. Contractors "must be registered and bonded with the Village of Palatine and where applicable with the State of Illinois" (Residential Submittal Requirements). Registration is done exclusively online via the CSS portal (https://citizen.palatine.il.us). All contractor registrations expire December 31 each calendar year regardless of bond end date. Published registration fees (CY 2024): general contractor $269/year; all other contractors $67/year. Electrical: the Village accepts electrical licenses from Elgin, Libertyville, Orland Park (Supervisory Electrician Certificate only), Schaumburg, Ottawa, Woodstock, Chicago, and ICC Master Electrician (R16-2023). Plumbing: licensed plumbers must include a notarized letter of intent on business stationery with signature and corporate seal (if incorporated) with permit applications. Lead paint: contractors disturbing lead-based paint in pre-1978 structures must be EPA RRP-certified. A completed Building Permit Contractor List form is required before permit issuance (not at application).',
    'notable_quirks' => '(1) No historic-district hurdles: the Village\'s Historic Palatine page states "There is no Historical Preservation Ordinance, Plan, District or Commission in Palatine" — remodels follow standard Village ordinances only. (2) Contractor bonding: registration requires a bond filed with the Village (registrations expire Dec 31 regardless of bond end date). (3) Fire sprinklers: "A residential sprinkler system is required for all new residential construction and may be required if exposed engineered wood floor joists are used in remodeling projects" — directly relevant to basement finish jobs. (4) Energy testing on remodels: duct leakage and blower door tests per 2021 IECC with Illinois amendments can apply to additions/alterations, and the CO is held until passing reports are submitted. (5) Trade rough inspections must all be approved before the rough frame inspection, and the approved job-copy plans must be on site or the inspection fails; failed or un-canceled inspections incur a $72 re-inspection fee. (6) Interior-only remodels are exempt from the plat-of-survey requirement. (7) Paper applications are not accepted — everything runs through the CSS (EnerGov) portal. (8) Plumbing inspections are only offered Mondays and Thursdays. (9) Express permits are valid only 90 days from issuance. (10) Plumber\'s notarized letter of intent is required with permit applications.',
    'researched_at' => '2026-07-14',
  ],
  'schaumburg' => 
  [
    'town' => 'Schaumburg',
    'source_urls' => 
    [
      0 => 'https://www.villageofschaumburg.com/government/community-development/permit-services',
      1 => 'https://www.villageofschaumburg.com/government/community-development/permit-services/residential-permits',
      2 => 'https://www.villageofschaumburg.com/government/community-development/permit-services/residential-permits/alteration-basement-bathroom-kitchen-resource-guide',
      3 => 'https://www.villageofschaumburg.com/government/community-development/permit-services/residential-permits/basement-alteration-resource-guide',
      4 => 'https://www.villageofschaumburg.com/government/community-development/permit-services/residential-permits/bathroom-alteration-resource-guide',
      5 => 'https://www.villageofschaumburg.com/government/community-development/permit-services/residential-permits/kitchen-alteration-resource-guide',
      6 => 'https://www.villageofschaumburg.com/government/community-development/permit-services/residential-permits/addition-resource-guide',
      7 => 'https://www.villageofschaumburg.com/government/community-development/permit-services/permit-services-q-a',
      8 => 'https://www.villageofschaumburg.com/government/finance/license/contractor-s-business-license',
      9 => 'https://www.villageofschaumburg.com/government/community-development/planning-zoning/olde-schaumburg-centre-osc-historic-district',
    ],
    'permit_when_required' => 'Per the official site, "Additions, alterations, and new construction projects require a permit" and plan reviews are conducted for these. Specifics by project: KITCHEN — "If you are planning to remodel your kitchen, a permit is required. An electrical permit is also required for the electrical work to be performed." BATHROOM — a permit is required to remodel a bathroom, BUT "Permits are not required for countertop replacement, refacing of existing cabinets or replacement of cabinets same as existing layout with no electrical or plumbing changes. However, a permit may be required whenever bathroom cabinets are replaced or added." BASEMENT — "Building permits are required for a finished basement when any walls are being built, moved or altered and/or a change of use in the proposed area (including hanging gypsum board on walls and/or ceiling). Permits are required if any electrical, HVAC, plumbing or gas piping is being performed." ADDITIONS — "A permit is required to construct an addition on your premise." Whenever remodeling a basement, bathroom or kitchen, a Residential Building Permit must be submitted and a plan review conducted, with a detailed drawing and written scope of work. Cosmetic exceptions published: window replacement needs no permit "if there are no changes to the size and location of the existing exterior window openings and no new openings are proposed." Water heaters DO require a permit. Express Permits (no plan review) are available only for roofing, siding, air conditioner, furnace, water heater, sewer repair, and plumbing. Small improvements (decks, fences, patios, pools, sidewalks, stoops) also require permits. Land Development permits (Engineering Division) required for lot grading/regrading, retaining walls, underdrains and sump pump piping.',
    'application_process' => 'Online via the OpenGov portal (schaumburgil.portal.opengov.com) — "All residential building permits have moved to the OpenGov portal, other than demolition." Applicants create an OpenGov account and submit the Residential Building Permit application; demolition, multi-family HOA, or multi-location submittals go through Permit Services at 847-923-4420 / permits@schaumburg.com. The village is phasing all permit types into OpenGov ("one-stop shop"). Published 4-step process: (1) Online submittal — detailed drawings + written scope of work; plat of survey (legible, dimensioned, scope highlighted) when applicable; signed/approved Homeowner\'s Association Form for exterior projects if the residence is HOA-governed; single collated PDF drawing set digitally stamped/signed by architect and engineer of record — EXCEPT projects under $10,000 construction cost with no structural modifications; (2) Prescreen and technical plan review, corrections issued as a plan review letter through the portal; (3) Payment and issuance — fees paid online (credit card 2.9% + $0.30 service fee, or e-check $2.25) or in person; (4) Inspections. Applications also published in Hindi, Gujarati, Spanish, and Polish (email to permits@schaumburg.com). Construction valuation is checked against R.S. Means square-foot costs (must be within 10%); undervalued submittals may be repriced by the village.',
    'review_time' => 'Published on the Permit Services Q&A page: "Ten (10) business days is the goal for the plan review" for residential permits; peak season is spring through summer, so include a minimum of ten business days in the project schedule. "All plan reviews are processed in date order received. There are no expedited options." Express Permits (re-roofs, siding, AC, furnace, water heater) are issued without plan review.',
    'inspections' => 'All inspections require a minimum 24-hour advance notice; schedule up to 4 p.m. on the business day prior via the OpenGov portal or by calling Permit Services at 847-923-4420. Published sequences: KITCHEN and BATHROOM — rough plumbing/mechanical/electrical/framing; insulation inspection; final plumbing/mechanical/electrical/framing. Bathroom guide adds a pre-start step: "Field verify code compliance of plumbing and electrical prior to start of project by setting up a Meeting on Site once the permit is issued." BASEMENT — rough framing/electrical/mechanical/plumbing; ceiling inspection (for suspended ceilings); insulation; final framing/electrical/mechanical/plumbing. ADDITION — prepour (before all footing, foundation and slab pours); rough (framing, plumbing, electrical, mechanical); insulation; active roofing; final. Construction must remain accessible and exposed until approved by the inspector; the printed permit card and approved-as-noted permit set must be visible/available on site; J.U.L.I.E. (811) must be called at least 48 hours before any digging.',
    'fees' => 'Published per-project fee for kitchen alterations, bathroom alterations, basement alterations, AND additions: "1% of construction value. $100 minimum, and $4,600 maximum fee." Complete fee schedule is in Village Code Title 3 Ch. 41 §41.01 (Municode link from the village site). Online payment service fees: credit card 2.9% + $0.30; e-check $2.25. Out-of-town Contractor\'s Business License: $125/year (includes required $10 Schaumburg Business Association fee), prorated to $67.50 July–November.',
    'contractor_registration' => 'Yes — "A Contractor\'s Business License is required for all contractors performing work in the Village of Schaumburg" before a permit can be issued. "There is no bond or insurance required." Out-of-town contractors receive an "Out of Town Contractors License" ($125/year incl. $10 SBA fee; prorated $67.50 July–Nov; valid through Dec. 31; renewals open ~Nov. 15). Contractors based in Schaumburg apply for a regular Business License or Home Based Business License instead. Exception: plumbers and roofers are licensed by the State of Illinois, not the village — current copies of state licenses must be submitted prior to permit issuance. All plumbing permit applications must include a letter of intent on the licensed plumber of record\'s business stationery with signature and corporate seal (or notarized if not incorporated), per 225 ILCS 320/37.',
    'notable_quirks' => '(1) Olde Schaumburg Centre (OSC) Historic District around Schaumburg Rd/Roselle Rd: design within the district and designated landmark buildings is evaluated under the OSC Design Manual (adopted 2005); the village publishes an OSC Architectural Resource Guide and lists local landmark and contributing buildings. (2) No contractor bond or insurance is required — unusual for Chicago suburbs. (3) Anti-lowball valuation rule: submitted construction cost must be within 10% of R.S. Means published square-foot costs or the village may reprice it / demand certified proposals. (4) HOA overlay: exterior projects on HOA-governed residences require the village\'s Homeowner\'s Association Form approved on HOA letterhead. (5) Architect/engineer digital seal required on all sheets except projects under $10,000 with no structural work. (6) Formal written code-interpretation appeal process (Village Ordinance §153.03.1). (7) Village Hall is temporarily at 1000 E. Woodfield Rd. (\\"Temporary Village Hall\\"). (8) Permit software is mid-migration: residential permits are live on OpenGov; other types are being phased in. METHOD NOTE: villageofschaumburg.com blocks automated access (Akamai 403), so all pages were read via Internet Archive snapshots of the official pages dated Feb 1 – May 16, 2026; verify current fees against the live site or Municode §41.01 before publishing.',
    'researched_at' => '2026-07-14',
  ],
  'wilmette' => 
  [
    'town' => 'Wilmette',
    'source_urls' => 
    [
      0 => 'https://www.wilmette.gov/189/Residential-Permits',
      1 => 'https://www.wilmette.gov/177/Permits-Construction',
      2 => 'https://www.wilmette.gov/191/Permit-Submittals',
      3 => 'https://www.wilmette.gov/193/Target-Timeframes-to-Permit-Review',
      4 => 'https://www.wilmette.gov/190/Permit-Fees-Extensions',
      5 => 'https://www.wilmette.gov/181/Building-Inspections',
      6 => 'https://www.wilmette.gov/179/Applications-Forms',
      7 => 'https://www.wilmette.gov/185/Contractor-Licensing-Requirements',
      8 => 'https://www.wilmette.gov/183/Construction-Requirements',
      9 => 'https://www.wilmette.gov/350/Historic-Preservation-Commission',
      10 => 'https://www.wilmette.gov/171/Historic-Preservation-Resources',
      11 => 'https://www.wilmette.gov/DocumentCenter/View/3941/',
      12 => 'https://www.wilmette.gov/DocumentCenter/View/92/What-is-a-Certificate-of-Appropriateness-PDF',
    ],
    'permit_when_required' => 'Permits ARE required for (Residential Permits page list): remodeling, additions, new construction, demolitions, electrical work, plumbing, HVAC/air conditioning/furnace, drain tile/basement waterproofing, decks, patios, roofing, fencing, generators, EV chargers, grading, swimming pools/spas, dumpsters, portable storage containers, security/alarms, sidewalks, and any work in the public right-of-way. This means kitchen, bath, and basement remodels involving electrical, plumbing, or structural changes need permits. Permits are NOT required for (cosmetic work, though it must still meet zoning regulations): flooring replacement, window/door replacement in single-family homes, gutters/downspouts, driveway seal coating, sheds 64 sq ft or less, playhouses under 64 sq ft, satellite dishes 18 inches or smaller, window air conditioners, free-standing basketball hoops, flag poles, temporary ice rinks, playground equipment. The village says "When in doubt" contact Community Development at 847-853-7550.',
    'application_process' => 'Apply to the Community Development Department at Village Hall, 1200 Wilmette Avenue (847-853-7550, comdev@wilmette.com). Paper submittals are preferred; electronic submittals by email to comdev@wilmette.com are acceptable "for most but not all project types," and the village notes permits filed electronically will take longer for issuance. Online payments are handled through the Munis Citizen Self Service portal (wilmette.munisselfservice.com, Permits & Inspections module). Required documents per the Permit Submittals page: permit application (Pages A/B/C), a boundary plat of survey conforming to Illinois minimum standards (not marked "for mortgage" use), and drawings. An Illinois Registered Architect or Structural Engineer signature and stamp is required on drawings when the project involves structural work OR construction cost exceeds $25,000; for projects under $25,000, the plan reviewer has discretion to require a stamp for complex work "like kitchens, baths, new window openings, and basement remodeling." A Permit Application Checklist and the Single-Family Construction and Permit Handbook are on the Applications & Forms page.',
    'review_time' => 'Published target: "the village has a goal of 10 business days for each reviewer to complete the first review" for most projects. Same-day or next-day issuance is offered for single-family fences, roofs, dumpsters and portable storage containers on private property, and water/sewer repairs. The site also states permits filed electronically will take longer for issuance.',
    'inspections' => 'Inspections are required to verify work meets applicable codes; scheduling is by PHONE ONLY at 847-853-7550, at least 24 hours in advance, and must be confirmed over the phone (a voicemail does not count as scheduled). Provide project number, inspection type, desired day/time, and contact info. Building, electrical, and plumbing inspections run Monday-Friday, 8:30 am-noon and 1-3 pm. The Building Inspections page lists 25+ common inspection types including tree pre-construction, footings, foundation, framing rough, plumbing rough, electrical rough, mechanical rough, and separate final inspections for construction, plumbing, electrical, and mechanical. Per the 2026 fee schedule, each inspection and re-inspection costs $39. Certificate of occupancy procedures: not published on the pages read.',
    'fees' => 'Published in the 2026 Construction-Related Fee Schedule (effective Jan 1, 2026, issued 12/22/2025). Base building permit fee: $20.16 per $1,000 of estimated job value. Single-family permit DEPOSITS due at application: new construction $900; additions $591; remodeling/detached garages/generators/pools $118. Plan examination fees (deducted from the deposit at issuance): single-family new construction $202; additions $118; remodeling/detached garages/generators/pools $79. Inspection and re-inspection: $39 each. Trade fees: electrical base $45 plus $1.15 per outlet/switch/receptacle, service installations $34 (100A)/$45 (200A)/$62 (400A); mechanical base $45, A/C $39 per unit; plumbing base $45 plus $8 per fixture (incl. water heater, water closets). Fence permit $39; roofing permit $39; demolition of principal structure $4,500. Engineering: grading permit $235 (new construction/additions/detached garages) or $120 (other), re-review $80; right-of-way permit $62 plus $1,000 refundable protection deposit; dumpster/POD on private property $45. Most permits are valid 12 months; fence, roof, tree removal, dumpster and POD permits are valid 6 months and grading permits 18 months; extension fee is 1/12th of the original permit fee per month/30 days after expiration. Surcharge for working without a permit: $153 or 50% of the permit cost, whichever is greater.',
    'contractor_registration' => 'Yes — "All contractors on a building permit must have a Wilmette contractors\' license before a building permit will be issued." The license is calendar-year based, renewed annually, with an $80 fee plus a completed application. Trade-specific add-ons: electrical contractors must provide a current local or City of Chicago electrical license; plumbing contractors are exempt from the $80 fee but must provide a state or City of Chicago Journeyman Plumbers License plus State of Illinois Certificate of Registration; roofing contractors must provide a current state roofing license; sewer contractors need a state or Chicago sewer license, a $10,000 bond, and a certificate of insurance; lawn sprinkler contractors need an IDPH certificate, $10,000 bond, insurance, and journeyman plumber license. Any contractor working in the public right-of-way must provide a certificate of insurance listing the Village of Wilmette as additional insured. Contractors disturbing lead paint in pre-1978 homes must be USEPA (RRP) certified.',
    'notable_quirks' => '1) Historic preservation: a Certificate of Appropriateness (no fee) from the Historic Preservation Commission is required BEFORE beginning exterior work on a Wilmette Local Landmark — additions, alterations, removals, exterior repairs, relocations — and is required even when no building permit is needed; staff may issue CoAs for in-kind repairs/maintenance; unapproved work can draw a stop work order. Three areas of the village are designated National Register Historic Districts. The Village also has a separate Appearance Review Commission, with a published handbook and application. 2) Architect/structural engineer stamp required at a relatively low threshold: structural work OR cost over $25,000, with reviewer discretion to require it for kitchens, baths, new window openings, and basement remodels under $25,000. 3) Permit deposits are due at application (e.g., $118 for single-family remodeling, $591 for additions), with plan-exam fees deducted from them. 4) Paper submittals are preferred and electronic filings are stated to take longer to issue. 5) Inspections are phone-scheduled only and must be verbally confirmed. 6) Site development plan required for excavation deeper than 3 ft or over 100 sq ft; JULIE dig number required for any excavation; construction signage required at all sites; 24-hour written neighbor notice before principal-structure demolition. 7) $1,000 refundable right-of-way protection deposit when working in the ROW. 8) Unpermitted-work surcharge of $153 or 50% of permit cost.',
    'researched_at' => '2026-07-14',
  ],
  'winnetka' => 
  [
    'town' => 'Winnetka',
    'source_urls' => 
    [
      0 => 'https://www.villageofwinnetka.org/159/Building-Permits-Construction',
      1 => 'https://www.villageofwinnetka.org/170/Building-Permit-Applications-Work-Requir',
      2 => 'https://www.villageofwinnetka.org/169/Work-Not-Requiring-Permits',
      3 => 'https://www.villageofwinnetka.org/164/Inspections-Permit-Fees',
      4 => 'https://www.villageofwinnetka.org/166/Contractor-Licensing-Bonding-Requirement',
      5 => 'https://www.villageofwinnetka.org/faq.aspx?TID=18',
      6 => 'https://www.villageofwinnetka.org/DocumentCenter/View/2341/Permit-Fees-Deposits-and-Bonds-PDF',
      7 => 'https://www.villageofwinnetka.org/270/Landmark-Preservation-Commission',
    ],
    'permit_when_required' => 'Per the official site: a permit is required to remove, relocate, construct or alter building walls or perform any other structural alterations, and for any work involving mechanical, electrical, or plumbing systems. Specifically for interior remodels (kitchens/baths/basements): construction of new walls, removal of existing walls, or removal/replacement of existing wall or ceiling covering (drywall, plaster) of 100 sq ft or greater; new electrical circuits, circuit extensions, or hard-wired devices; modifications to plumbing waste/drain/vent lines, water supply lines, or mechanical ductwork. Basement finishes/remodels require a permit when they involve wall construction, electrical circuits, plumbing, or ductwork. Additions require a permit regardless of size. Cosmetic work exempt (Work Not Requiring Permits page): \'replacing plumbing and lighting fixtures, carpeting, floor refinishing, painting, installing cabinets and shelving\'; cabinet replacement is exempt provided no electrical work is included and plumbing fixtures use existing supply and drain lines; fixture replacement on existing supply/drain lines; selective trim/stair-tread replacement so long as no more than 100 sq ft of wall finish is removed; in-kind window replacement in existing openings (must still meet Illinois Energy Conservation Code); most siding repair/replacement (stucco/EIFS installation DOES require a permit). The Village encourages calling Community Development (847-716-3520) before any work to confirm whether a permit is required.',
    'application_process' => 'No online permit portal is named anywhere on the official pages read. Applications are Village PDF forms downloaded from the Building Permit Applications page — e.g., Single Family Residential Remodeling Permit Application, Single Family Residential Addition, Basement Finish or Remodel, Electrical Miscellaneous & Service, Plumbing Miscellaneous — submitted to the Community Development Department, 510 Green Bay Road, Winnetka, IL 60093 (permit technicians: Stacy Kelly 847-716-3527 / skelly@winnetka.org; Jessica Polony 847-716-3529 / jpolony@winnetka.org). Residential interior remodels/repairs and additions must include a completed Scope of Work form; supporting forms include Contractor List, Authorized Designee, Change of Contractor, MEP Permit Fee Worksheets, and Zoning Calculation Worksheets. A Community Development representative emails or calls the primary contact on the application once the permit is approved. Permits are valid 15 months; a 9-month extension is available if requested before expiration with payment of 50% of the original permit fee.',
    'review_time' => 'Published on the official FAQ: interior remodeling projects typically take 2 to 3 weeks; new home construction or additions typically take 3 weeks for initial plan review; driveway/fence applications take 2-3 business days; revision submittals add 7-10 business days.',
    'inspections' => 'The official Inspections & Permit Fees page states only that \'inspection requirements vary depending on the type of project\' — a specific inspection type list/sequence for remodels is not published. Inspections are scheduled by phoning the Permit/Zoning Technician at 847-716-3527 with at least 24 hours advance notice, providing contact name, phone, job site address, inspection type, and Village permit number.',
    'fees' => 'Published: effective January 1, 2024, all major permits — new building, remodeling, and addition projects — are calculated at 3% of the estimated value of improvements (shown on the fees page as $30 per $1,000 of construction cost, $100 minimum for remodeling, decks, sheds, new construction). Applicants must be prepared to justify the estimated value; the Community Development Director may base the fee on the applicant\'s estimate, an architect\'s/engineer\'s cost certification, an owner affidavit, or an RS Means Square Foot Costs calculation. As of the 2024 change, separate add-on fees previously collected with major permits (roofs, electrical outlets, plumbing fixtures, HVAC equipment, impermeable surfaces) are no longer collected on those permits. Standalone sample fees published on the site: fence $85; roofing $85; impermeable surface $75; plumbing $90 base for 5 fixtures + $13 per additional fixture; furnace/AC $100 base + $120 per unit; pool $680; electric service listed verbatim as \'$13,200 (200 amp service) / $26,000 (400 amp service)\' (as printed on the Village page). Project-specific fees: contact the Permit Coordinator at 847-716-3520. The complete fee resolution is available on the Village website or by request.',
    'contractor_registration' => 'The Village of Winnetka does not maintain a contractor licensing program; it accepts licenses issued by the State of Illinois or by other municipalities that test licensees. Electrical, plumbing, irrigation, roofing, and fire suppression contractors must have current licenses on file with the Village. No general-contractor registration requirement is published.',
    'notable_quirks' => '(1) Right-of-way bond: a $25,000 License and Permit Bond must be filed with Community Development before permit issuance, but only when the permit includes work on Village property or within a public right-of-way; the owner or GC files it (or the subcontractor doing the ROW work if there is no GC). (2) Historic preservation: the Historic/Landmark Preservation Commission reviews applications for alterations affecting designated landmarks and reviews demolition permit applications, deciding whether a Historic and Architectural Impact Study (HAIS) must be conducted before a demolition permit is issued — relevant to additions/gut projects involving demolition. (3) Per the Village FAQ, exterior work on commercial, multi-family, or institutional buildings requires permits — the official pages do not apply any extra design review to single-family interior remodels. (4) The 100 sq ft drywall/plaster threshold is the bright line between cosmetic work and a permit-required interior remodel. (5) Fee basis audit: the Village may independently verify your stated construction value via RS Means. (6) Permits expire after 15 months; extension costs 50% of the original fee.',
    'researched_at' => '2026-07-14',
  ],
];
